"""Mars Lesson 9 house source knowledge — WHERE I APPLY EFFORT."""

from __future__ import annotations

from app.services.mars_source_knowledge import MarsSourceFactDef, _f

REF_H1 = "lesson9_mars_house_1"
REF_H2 = "lesson9_mars_house_2"
REF_H3 = "lesson9_mars_house_3"
REF_H4 = "lesson9_mars_house_4"
REF_H5 = "lesson9_mars_house_5"
REF_H6 = "lesson9_mars_house_6"
REF_H7 = "lesson9_mars_house_7"
REF_H8 = "lesson9_mars_house_8"
REF_H9 = "lesson9_mars_house_9"
REF_H10 = "lesson9_mars_house_10"
REF_H11 = "lesson9_mars_house_11"
REF_H12 = "lesson9_mars_house_12"


def _h(
    fact_id: str,
    house: str,
    category: str,
    text: str,
    polarity: str,
    scope: str,
    *tags: str,
    source_reference: str,
    activation_condition: str | None = None,
    unresolved: bool = False,
) -> MarsSourceFactDef:
    return _f(
        fact_id,
        house,
        category,
        text,
        polarity,
        scope,
        *tags,
        source_reference=source_reference,
        factor_type="house",
        activation_condition=activation_condition,
        unresolved=unresolved,
    )


HOUSE_1_PACK: tuple[MarsSourceFactDef, ...] = (
    _h("mars_h1_executes_personally_own_hands", "1", "execution",
       "Often executes personally / does things with own hands.",
       "strength", "WORK_CORE", "hands_on_execution", source_reference=REF_H1),
    _h("mars_h1_source_analytical_abilities", "1", "execution",
       "Source mentions analytical abilities in this action context; not Mercury analytical thinking "
       "and not a validated competency.",
       "strength", "WORK_DETAIL", source_reference=REF_H1),
    _h("mars_h1_direct_uncompromising_toward_delay", "1", "execution",
       "Directness, honesty, and an uncompromising attitude toward delay / stagnation.",
       "strength", "WORK_CORE", source_reference=REF_H1),
    _h("mars_h1_entrepreneurial_forceful_assertive", "1", "initiative",
       "Entrepreneurial drive: forceful, bold, assertive.",
       "strength", "WORK_CORE", source_reference=REF_H1),
    _h("mars_h1_asserts_self_views_action_and_thinking_style", "1", "initiative",
       "Ability to assert self, views, action style, and thinking style. This is self-assertion "
       "in action, not a thinking-category fact.",
       "strength", "WORK_CORE", source_reference=REF_H1),
    _h("mars_h1_metal_solder_forge_hand_work", "1", "work_conditions",
       "Ability to work with metal / solder / forge / use hands; not a certified skill claim.",
       "strength", "WORK_CORE", source_reference=REF_H1),
    _h("mars_h1_tends_not_to_postpone_tasks", "1", "continuation",
       "Tends not to postpone tasks.",
       "strength", "WORK_CORE", source_reference=REF_H1),
    _h("mars_h1_aggression_rudeness_recklessness_under_defeat", "1", "watchout",
       "Aggression / rudeness / lack of restraint / recklessness under defeat; "
       "not a deterministic accusation.",
       "risk", "WORK_CORE", source_reference=REF_H1),
    _h("mars_h1_weak_long_term_strategy", "1", "execution",
       "Source describes weak long-term strategy / difficulty planning far ahead.",
       "risk", "WORK_CORE", source_reference=REF_H1),
    _h("mars_h1_source_athletic_lean_muscular_appearance", "1", "source_specific",
       "Source association with athletic / lean / muscular appearance; not a body or hiring claim.",
       "neutral", "SOURCE_ONLY", source_reference=REF_H1),
    _h("mars_h1_source_close_ascendant_surgical_birth", "1", "source_specific",
       "Source describes a close-to-Ascendant surgical-birth claim; not a medical diagnosis.",
       "risk", "SOURCE_ONLY", source_reference=REF_H1),
)

HOUSE_2_PACK: tuple[MarsSourceFactDef, ...] = (
    _h("mars_h2_active_in_obtaining_material_benefits", "2", "effort",
       "Active in obtaining material benefits. This is money activity, not financial skill.",
       "strength", "WORK_CORE", source_reference=REF_H2),
    _h("mars_h2_push_for_discounts", "2", "execution",
       "Ability to push for discounts; not a validated negotiation competency.",
       "strength", "WORK_DETAIL", source_reference=REF_H2),
    _h("mars_h2_prefers_tangible_usable_things", "2", "work_conditions",
       "Prefers tangible / directly usable things.",
       "strength", "WORK_CORE", source_reference=REF_H2),
    _h("mars_h2_prefers_working_for_oneself", "2", "work_conditions",
       "Preference for working for oneself, ideally without bosses or subordinates.",
       "strength", "WORK_CORE", "independent_execution", source_reference=REF_H2),
    _h("mars_h2_occupation_associations", "2", "professional_association",
       "Source-described occupation associations include dentist, cutter / seamstress, firefighter, "
       "businessperson, military, and engineer; not career assignments.",
       "neutral", "WORK_DETAIL", source_reference=REF_H2),
    _h("mars_h2_earning_becomes_battlefield", "2", "effort",
       "Earning money becomes a battlefield / exhausting energy expenditure.",
       "risk", "WORK_CORE", source_reference=REF_H2),
    _h("mars_h2_spending_may_dominate_accumulation", "2", "watchout",
       "Spending may dominate accumulation.",
       "risk", "WORK_CORE", source_reference=REF_H2),
    _h("mars_h2_impulsive_spending_after_work_saving", "2", "watchout",
       "Impulsive spending after periods of work / saving.",
       "risk", "WORK_CORE", source_reference=REF_H2),
    _h("mars_h2_desire_to_work_hard_to_apply_constructively", "2", "stuck_blocker",
       "Desire to work exists but may be difficult to apply constructively.",
       "risk", "WORK_CORE", source_reference=REF_H2),
    _h("mars_h2_periodic_financial_self_sabotage", "2", "watchout",
       "Periodic financial self-sabotage.",
       "risk", "WORK_CORE", source_reference=REF_H2),
    _h("mars_h2_strong_harmonious_positive_budget_through_activity", "2", "effort",
       "Source condition “strong / harmonious Mars”: higher chance of a positive budget through "
       "activity / dynamism. No Mars-strength resolver is applied.",
       "conditional", "WORK_DETAIL",
       source_reference=REF_H2,
       activation_condition="strong_harmonious_mars_unresolved",
       unresolved=True),
)

HOUSE_3_PACK: tuple[MarsSourceFactDef, ...] = (
    _h("mars_h3_inventive_assertive_mind_in_action", "3", "execution",
       "Inventive / active / assertive mind in an action context. This is not analytical thinking.",
       "strength", "WORK_CORE", source_reference=REF_H3),
    _h("mars_h3_quickly_concentrates_on_interesting_subject", "3", "execution",
       "Can quickly concentrate on an interesting subject.",
       "strength", "WORK_CORE", source_reference=REF_H3),
    _h("mars_h3_strong_persuasion_in_conversation", "3", "execution",
       "Strong persuasion in conversation; not a validated persuasion competency.",
       "strength", "WORK_DETAIL", source_reference=REF_H3),
    _h("mars_h3_obtains_outcome_through_conversation", "3", "execution",
       "Can obtain a desired outcome through conversation.",
       "strength", "WORK_CORE", source_reference=REF_H3),
    _h("mars_h3_thought_described_as_sharpened", "3", "source_specific",
       "Thought described as sharpened. This is action-context wording, not a thinking category.",
       "neutral", "WORK_DETAIL", source_reference=REF_H3),
    _h("mars_h3_good_memory_for_details", "3", "execution",
       "Good memory for details in this action context; not a Mercury memory tag.",
       "strength", "WORK_DETAIL", source_reference=REF_H3),
    _h("mars_h3_attention_to_detail", "3", "execution",
       "Attention to detail.",
       "strength", "WORK_CORE", source_reference=REF_H3),
    _h("mars_h3_curiosity_through_action_and_contact", "3", "initiative",
       "Curiosity expressed through action / contact.",
       "strength", "WORK_CORE", source_reference=REF_H3),
    _h("mars_h3_occupation_associations", "3", "professional_association",
       "Source-described occupation associations include journalism, commentary, literature, "
       "teaching, and driving; not career assignments or driving skill.",
       "neutral", "WORK_DETAIL", source_reference=REF_H3),
    _h("mars_h3_tactlessness_impatience_criticism", "3", "watchout",
       "Tactlessness / impatience / criticism.",
       "risk", "WORK_CORE", source_reference=REF_H3),
    _h("mars_h3_argumentative_imposes_opinion_sharp_speech", "3", "conflict",
       "Argumentative; imposes opinion / sharp speech. This is not persuasion.",
       "risk", "WORK_CORE", source_reference=REF_H3),
    _h("mars_h3_start_and_completion_scatter", "3", "stuck_blocker",
       "Difficulty starting and completing because energy scatters.",
       "risk", "WORK_CORE", source_reference=REF_H3),
    _h("mars_h3_source_transport_accidents_injuries", "3", "source_specific",
       "Source association with transport accidents / injuries; not a prediction or diagnosis.",
       "risk", "SOURCE_ONLY", source_reference=REF_H3),
    _h("mars_h3_harmonious_mars_fast_driving", "3", "source_specific",
       "Source condition “harmonious Mars”: this may manifest simply as fast driving. "
       "Not a driving skill. No Mars-harmony resolver is applied.",
       "conditional", "SOURCE_ONLY",
       source_reference=REF_H3,
       activation_condition="harmonious_mars_unresolved",
       unresolved=True),
)

HOUSE_4_PACK: tuple[MarsSourceFactDef, ...] = (
    _h("mars_h4_high_activity_in_home_life", "4", "work_conditions",
       "High activity / dynamics in home life.",
       "strength", "WORK_CORE", source_reference=REF_H4),
    _h("mars_h4_physical_sport_equipment_at_home", "4", "work_conditions",
       "Physical / sport equipment at home.",
       "neutral", "WORK_CORE", source_reference=REF_H4),
    _h("mars_h4_dislikes_others_imposing_home_order", "4", "work_conditions",
       "Dislikes others imposing order in own home.",
       "strength", "WORK_CORE", source_reference=REF_H4),
    _h("mars_h4_builds_own_domestic_order", "4", "execution",
       "Builds own domestic order / world.",
       "strength", "WORK_CORE", source_reference=REF_H4),
    _h("mars_h4_frequent_repairs_home_in_motion", "4", "effort",
       "Frequent repairs / remodeling / home constantly in motion.",
       "strength", "WORK_CORE", source_reference=REF_H4),
    _h("mars_h4_recurring_physical_effort_at_home", "4", "effort",
       "Recurring physical effort at home: repairs / rearranging.",
       "risk", "WORK_CORE", source_reference=REF_H4),
    _h("mars_h4_conflicts_with_family", "4", "conflict",
       "Conflicts with family.",
       "risk", "WORK_CORE", source_reference=REF_H4),
    _h("mars_h4_struggle_with_parental_authority_traditions", "4", "conflict",
       "Struggle with parental authority / traditions.",
       "risk", "WORK_CORE", source_reference=REF_H4),
    _h("mars_h4_difficulty_with_mandatory_payments", "4", "watchout",
       "Difficulty with mandatory payments.",
       "risk", "WORK_CORE", source_reference=REF_H4),
    _h("mars_h4_source_fire_destruction_risk", "4", "source_specific",
       "Source association with fire / destruction risk; not a prediction.",
       "risk", "SOURCE_ONLY", source_reference=REF_H4),
    _h("mars_h4_source_household_injury_theft_tragedy", "4", "source_specific",
       "Source association with household injury / theft / tragedy; not a prediction or diagnosis.",
       "risk", "SOURCE_ONLY", source_reference=REF_H4),
    _h("mars_h4_strong_affliction_domestic_tyranny", "4", "watchout",
       "Source condition “strong affliction”: domestic tyranny. Canonical only; not an accusation. "
       "No Mars-affliction resolver is applied.",
       "risk", "SOURCE_ONLY",
       source_reference=REF_H4,
       activation_condition="strong_affliction_unresolved",
       unresolved=True),
)

HOUSE_5_PACK: tuple[MarsSourceFactDef, ...] = (
    _h("mars_h5_excitement_risk_adventure", "5", "effort",
       "Excitement / risk / adventure. This is a risk context, not risk-tolerance scoring.",
       "strength", "WORK_CORE", source_reference=REF_H5),
    _h("mars_h5_competitive_spirit", "5", "conflict",
       "Competitive spirit.",
       "strength", "WORK_CORE", "competitive_drive", source_reference=REF_H5),
    _h("mars_h5_hobby_may_develop_into_profession", "5", "professional_association",
       "Hobby may develop into a profession; not a career assignment.",
       "neutral", "WORK_DETAIL", source_reference=REF_H5),
    _h("mars_h5_occupation_associations", "5", "professional_association",
       "Source-described occupation associations include business, casino dealer, fitness club, "
       "athlete, art expert, teacher, and profit from the entertainment / creative / sport / "
       "stage field; not career assignments.",
       "neutral", "WORK_DETAIL", source_reference=REF_H5),
    _h("mars_h5_impulsiveness_reckless_courage", "5", "watchout",
       "Impulsiveness / reckless courage.",
       "risk", "WORK_CORE", source_reference=REF_H5),
    _h("mars_h5_loves_competition_struggles_with_losing", "5", "conflict",
       "Loves competition but may struggle with losing.",
       "risk", "WORK_CORE", source_reference=REF_H5),
    _h("mars_h5_lack_of_patience", "5", "work_rhythm",
       "Lack of patience.",
       "risk", "WORK_CORE", source_reference=REF_H5),
    _h("mars_h5_activity_proceeds_in_bursts", "5", "work_rhythm",
       "Activity proceeds in bursts.",
       "risk", "WORK_CORE", "activity_bursts", source_reference=REF_H5),
)

HOUSE_6_PACK: tuple[MarsSourceFactDef, ...] = (
    _h("mars_h6_difficult_task_tolerance", "6", "effort",
       "Constructive workaholism: does not fear difficult or labor-intensive assignments.",
       "strength", "WORK_CORE", "difficult_task_tolerance", source_reference=REF_H6),
    _h("mars_h6_tools_machinery_work", "6", "work_conditions",
       "Work with metal objects, tools, equipment / technology.",
       "strength", "WORK_CORE", source_reference=REF_H6),
    _h("mars_h6_rarely_leads", "6", "execution",
       "Source says rarely leads.",
       "neutral", "WORK_CORE", source_reference=REF_H6),
    _h("mars_h6_does_work_personally", "6", "execution",
       "More often executes personally.",
       "strength", "WORK_CORE", "hands_on_execution", source_reference=REF_H6),
    _h("mars_h6_personal_work_done_well", "6", "execution",
       "Source claims executing personally is done very well; not a validated competency.",
       "strength", "WORK_DETAIL", source_reference=REF_H6),
    _h("mars_h6_occupation_associations", "6", "professional_association",
       "Source-described occupation associations include surgeon, dentist, massage therapist, "
       "mechanic, worker, military, and firefighter; not career assignments.",
       "neutral", "WORK_DETAIL", source_reference=REF_H6),
    _h("mars_h6_workplace_conflict_pushes_line", "6", "conflict",
       "Workplace conflict: pushes own line / argues.",
       "risk", "WORK_CORE", "workplace_conflict", source_reference=REF_H6),
    _h("mars_h6_chronic_workplace_conflict", "6", "conflict",
       "Chronic workplace conflict.",
       "risk", "WORK_CORE", source_reference=REF_H6),
    _h("mars_h6_duties_constant_overload", "6", "work_conditions",
       "Duties may create constant overload / lack of breathing room.",
       "risk", "WORK_CORE", "effort_overload", source_reference=REF_H6),
    _h("mars_h6_source_illness_activity_imbalance", "6", "source_specific",
       "Source association with illness from too little or too much physical activity; "
       "not a medical diagnosis.",
       "risk", "SOURCE_ONLY", source_reference=REF_H6),
    _h("mars_h6_source_acute_inflammatory_illness", "6", "source_specific",
       "Source association with acute / inflammatory illness / fever; not a medical diagnosis.",
       "risk", "SOURCE_ONLY", source_reference=REF_H6),
)

HOUSE_7_PACK: tuple[MarsSourceFactDef, ...] = (
    _h("mars_h7_active_public_social_activity", "7", "work_conditions",
       "Active public / social activity.",
       "strength", "WORK_CORE", source_reference=REF_H7),
    _h("mars_h7_turn_enemies_into_friends_coworkers", "7", "conflict",
       "Ability to turn enemies into friends / coworkers.",
       "strength", "WORK_CORE", source_reference=REF_H7),
    _h("mars_h7_relationships_benefit_from_joint_energy_activity", "7", "work_conditions",
       "Work relationships benefit from energy-expending joint activity.",
       "strength", "WORK_CORE", source_reference=REF_H7),
    _h("mars_h7_sparring_sport_dance_association", "7", "professional_association",
       "Sparring-type sport / dance association; not a skill certification.",
       "neutral", "WORK_DETAIL", source_reference=REF_H7),
    _h("mars_h7_occupation_associations", "7", "professional_association",
       "Source-described occupation associations include negotiations, consulting, and dance "
       "teaching; not career assignments.",
       "neutral", "WORK_DETAIL", source_reference=REF_H7),
    _h("mars_h7_useless_competition_when_cooperation_required", "7", "conflict",
       "Useless competition when cooperation is required.",
       "risk", "WORK_CORE", source_reference=REF_H7),
    _h("mars_h7_provoke_conflict_or_attract_rude_behavior", "7", "conflict",
       "May provoke conflict in dialogue or attract rude conflict behavior.",
       "risk", "WORK_CORE", source_reference=REF_H7),
    _h("mars_h7_easily_enters_hostility_breaks_connections", "7", "conflict",
       "Easily enters hostility / breaks connections.",
       "risk", "WORK_CORE", source_reference=REF_H7),
    _h("mars_h7_perceived_as_aggressive_or_rough", "7", "watchout",
       "Others may perceive the person as aggressive / rough; not a deterministic identity.",
       "risk", "WORK_CORE", source_reference=REF_H7),
    _h("mars_h7_affliction_early_marriage_divorce", "7", "source_specific",
       "Source condition “under affliction”: early marriage / early divorce. Canonical only; "
       "not a relationship prediction. No Mars-affliction resolver is applied.",
       "risk", "SOURCE_ONLY",
       source_reference=REF_H7,
       activation_condition="affliction_unresolved",
       unresolved=True),
)

HOUSE_8_PACK: tuple[MarsSourceFactDef, ...] = (
    _h("mars_h8_cool_headed_action_in_emergencies", "8", "effort",
       "Skillful / cool-headed action in emergencies.",
       "strength", "WORK_CORE", "crisis_execution", source_reference=REF_H8),
    _h("mars_h8_mysticism_magic_energy_work_associations", "8", "professional_association",
       "Mysticism / magic / energy-work associations; not validated practices or job fit.",
       "neutral", "WORK_DETAIL", source_reference=REF_H8),
    _h("mars_h8_active_management_of_others_property", "8", "execution",
       "Active management of others' property. This is not a finance-skill claim.",
       "strength", "WORK_CORE", source_reference=REF_H8),
    _h("mars_h8_occupation_associations", "8", "professional_association",
       "Source-described occupation associations include business, politics, surgery, security, "
       "emergency response, finance, sport, and fund / asset management examples; "
       "not career assignments.",
       "neutral", "WORK_DETAIL", source_reference=REF_H8),
    _h("mars_h8_property_conflicts_may_resolve_dramatically", "8", "conflict",
       "Property conflicts may resolve dramatically / violently; not a violence prediction.",
       "risk", "WORK_CORE", source_reference=REF_H8),
    _h("mars_h8_aggression_over_others_money_inheritance", "8", "conflict",
       "Aggression over others' money / inheritance conflict; not a deterministic accusation.",
       "risk", "WORK_CORE", source_reference=REF_H8),
    _h("mars_h8_extreme_risk_situations", "8", "watchout",
       "Source describes extreme-risk situations. This is risk exposure, not risk-tolerance scoring.",
       "risk", "WORK_CORE", source_reference=REF_H8),
    _h("mars_h8_crises_from_misplaced_aggression", "8", "watchout",
       "Crises arising from misplaced aggression.",
       "risk", "WORK_CORE", source_reference=REF_H8),
    _h("mars_h8_excessive_effort_where_less_would_suffice", "8", "effort",
       "May create excessive effort where less would suffice.",
       "risk", "WORK_CORE", source_reference=REF_H8),
    _h("mars_h8_source_injury_fire_aggression_danger", "8", "source_specific",
       "Source association with injury / fire / aggression danger; not a prediction or diagnosis.",
       "risk", "SOURCE_ONLY", source_reference=REF_H8),
)

HOUSE_9_PACK: tuple[MarsSourceFactDef, ...] = (
    _h("mars_h9_expansion_through_competition_rivalry", "9", "conflict",
       "Expansion through competition / rivalry.",
       "strength", "WORK_CORE", "competitive_drive", source_reference=REF_H9),
    _h("mars_h9_travel_involving_physical_effort", "9", "work_conditions",
       "Travel involving physical effort: tourism, hiking, expeditions.",
       "strength", "WORK_CORE", source_reference=REF_H9),
    _h("mars_h9_drive_toward_distant_travel_and_knowledge", "9", "initiative",
       "Drive toward distant travel and knowledge.",
       "strength", "WORK_CORE", source_reference=REF_H9),
    _h("mars_h9_international_trade_goods_mechanisms", "9", "professional_association",
       "International trade involving manufactured goods / mechanisms; not a trade-skill claim.",
       "neutral", "WORK_DETAIL", source_reference=REF_H9),
    _h("mars_h9_work_abroad_association", "9", "work_conditions",
       "Work-abroad association; not a career assignment.",
       "neutral", "WORK_DETAIL", source_reference=REF_H9),
    _h("mars_h9_occupation_associations", "9", "professional_association",
       "Source-described occupation associations include military, coach, agitator, guide, teacher, "
       "politician, PR, lawyer, and media; not verified teaching ability or career assignments.",
       "neutral", "WORK_DETAIL", source_reference=REF_H9),
    _h("mars_h9_travel_accompanied_by_conflict_extremes", "9", "watchout",
       "Travel accompanied by conflict / extreme situations.",
       "risk", "WORK_CORE", source_reference=REF_H9),
    _h("mars_h9_ideological_disputes_may_escalate_physically", "9", "conflict",
       "Ideological disputes may escalate physically. This is not persuasion.",
       "risk", "WORK_CORE", source_reference=REF_H9),
    _h("mars_h9_imposing_views", "9", "conflict",
       "Imposing views.",
       "risk", "WORK_CORE", source_reference=REF_H9),
    _h("mars_h9_intolerance_toward_others_views", "9", "watchout",
       "Intolerance toward others' views.",
       "risk", "WORK_CORE", source_reference=REF_H9),
    _h("mars_h9_ideological_fanaticism", "9", "watchout",
       "Ideological fanaticism; not a diagnosis.",
       "risk", "WORK_CORE", source_reference=REF_H9),
    _h("mars_h9_repeated_disruptions_difficulty_staying_in_one_place", "9", "work_rhythm",
       "Repeated disruptions / difficulty staying in one place.",
       "risk", "WORK_CORE", source_reference=REF_H9),
    _h("mars_h9_worldview_may_change_sharply_after_conflict", "9", "watchout",
       "Worldview may change sharply after conflict / drama.",
       "risk", "WORK_CORE", source_reference=REF_H9),
)

HOUSE_10_PACK: tuple[MarsSourceFactDef, ...] = (
    _h("mars_h10_career_advancement_through_own_effort", "10", "execution",
       "Career advancement through own effort / independent struggle.",
       "strength", "WORK_CORE", "independent_execution", source_reference=REF_H10),
    _h("mars_h10_desire_to_work_independently_or_lead", "10", "initiative",
       "Desire to work independently or at least lead. Desire is not leadership competence.",
       "strength", "WORK_CORE", source_reference=REF_H10),
    _h("mars_h10_pioneer_opens_new_paths", "10", "execution",
       "Pioneer in own field; opens new paths.",
       "strength", "WORK_CORE", source_reference=REF_H10),
    _h("mars_h10_independently_pursues_goals", "10", "initiative",
       "Independently pursues goals.",
       "strength", "WORK_CORE", source_reference=REF_H10),
    _h("mars_h10_own_project_supports_initiative_leadership", "10", "work_conditions",
       "Own project supports initiative / leadership.",
       "strength", "WORK_CORE", source_reference=REF_H10),
    _h("mars_h10_source_leadership_association", "10", "professional_association",
       "Source leadership association; not a validated leadership competency.",
       "neutral", "WORK_DETAIL", source_reference=REF_H10),
    _h("mars_h10_business_prefers_tightly_unified_team", "10", "work_conditions",
       "In business, preference for a tightly unified team.",
       "strength", "WORK_CORE", source_reference=REF_H10),
    _h("mars_h10_occupation_associations", "10", "professional_association",
       "Source-described occupation associations include military / technical career, business, "
       "blacksmith, surgeon, emergency response, and dancer; not technical ability or "
       "career assignments.",
       "neutral", "WORK_DETAIL", source_reference=REF_H10),
    _h("mars_h10_ambition_push_for_power", "10", "watchout",
       "Ambition / push for power.",
       "risk", "WORK_CORE", source_reference=REF_H10),
    _h("mars_h10_may_pursue_power_at_others_expense", "10", "watchout",
       "May pursue power aggressively or at others' expense; not a deterministic accusation.",
       "risk", "WORK_CORE", source_reference=REF_H10),
    _h("mars_h10_authority_figures_hard_willful", "10", "work_conditions",
       "Authority figures may be hard / willful.",
       "risk", "WORK_CORE", source_reference=REF_H10),
    _h("mars_h10_uneven_career_disruptions_losses_delays", "10", "work_rhythm",
       "Uneven career: disruptions / losses / delays.",
       "risk", "WORK_CORE", source_reference=REF_H10),
    _h("mars_h10_job_changes_from_conflict_with_management", "10", "conflict",
       "Job changes because of conflict with management.",
       "risk", "WORK_CORE", source_reference=REF_H10),
    _h("mars_h10_rootless_solitary_struggle_pattern", "10", "watchout",
       "Source describes a rootless solitary struggle pattern.",
       "risk", "WORK_CORE", source_reference=REF_H10),
)

HOUSE_11_PACK: tuple[MarsSourceFactDef, ...] = (
    _h("mars_h11_hobbies_with_friends", "11", "work_conditions",
       "Hobbies with friends.",
       "neutral", "WORK_CORE", source_reference=REF_H11),
    _h("mars_h11_team_sports", "11", "work_conditions",
       "Team sports.",
       "neutral", "WORK_CORE", source_reference=REF_H11),
    _h("mars_h11_high_activity_in_group_work", "11", "effort",
       "High activity in group work.",
       "strength", "WORK_CORE", source_reference=REF_H11),
    _h("mars_h11_ignite_enthusiasm_in_groups", "11", "execution",
       "Ability to ignite enthusiasm in groups; not a validated leadership competency.",
       "strength", "WORK_DETAIL", source_reference=REF_H11),
    _h("mars_h11_initiative_driven_strong_willed_friends", "11", "work_conditions",
       "Initiative-driven / strong-willed friends.",
       "neutral", "WORK_CORE", source_reference=REF_H11),
    _h("mars_h11_leadership_in_group_context", "11", "initiative",
       "Leadership in friendship / group context. This is group-context action, not a job title.",
       "strength", "WORK_CORE", "leadership_action", source_reference=REF_H11),
    _h("mars_h11_struggle_for_better_future_reform", "11", "execution",
       "Struggle for a better future / reform.",
       "strength", "WORK_CORE", source_reference=REF_H11),
    _h("mars_h11_energy_oriented_toward_future", "11", "effort",
       "Energy oriented toward the future.",
       "strength", "WORK_CORE", source_reference=REF_H11),
    _h("mars_h11_occupation_associations", "11", "professional_association",
       "Source-described domain associations include instrumentation, mechanics, electronics, "
       "and social activity; not technical ability or career assignments.",
       "neutral", "WORK_DETAIL", source_reference=REF_H11),
    _h("mars_h11_adventurism_bluff_broken_hopes", "11", "watchout",
       "Adventurism / bluff / broken hopes.",
       "risk", "WORK_CORE", source_reference=REF_H11),
    _h("mars_h11_collective_projects_built_through_conflict", "11", "conflict",
       "Collective projects may be built through conflict / competition.",
       "risk", "WORK_CORE", source_reference=REF_H11),
    _h("mars_h11_rejection_of_existing_order_anarchic_tendency", "11", "watchout",
       "Rejection of existing order / anarchic tendency.",
       "risk", "WORK_CORE", source_reference=REF_H11),
    _h("mars_h11_defending_unrealistic_losing_ideas", "11", "watchout",
       "Defending unrealistic / losing ideas.",
       "risk", "WORK_CORE", source_reference=REF_H11),
    _h("mars_h11_conflicts_with_friends", "11", "conflict",
       "Conflicts with friends.",
       "risk", "WORK_CORE", source_reference=REF_H11),
)

HOUSE_12_PACK: tuple[MarsSourceFactDef, ...] = (
    _h("mars_h12_acts_behind_the_scenes", "12", "execution",
       "Acts behind the scenes.",
       "strength", "WORK_CORE", source_reference=REF_H12),
    _h("mars_h12_acts_in_solitude", "12", "work_conditions",
       "Acts in solitude.",
       "strength", "WORK_CORE", source_reference=REF_H12),
    _h("mars_h12_source_strategic_talent", "12", "execution",
       "Source claims strategic talent; not a validated job competence.",
       "strength", "WORK_DETAIL", source_reference=REF_H12),
    _h("mars_h12_anticipates_and_acts_secretly", "12", "execution",
       "Anticipates and acts secretly.",
       "strength", "WORK_CORE", source_reference=REF_H12),
    _h("mars_h12_ideal_driven_spiritually_meaningful_work", "12", "execution",
       "Ideal-driven / spiritually meaningful work.",
       "strength", "WORK_CORE", source_reference=REF_H12),
    _h("mars_h12_energy_fueled_by_secret_private_dreams", "12", "effort",
       "Energy may be fueled by secret / private dreams.",
       "conditional", "WORK_CORE", source_reference=REF_H12),
    _h("mars_h12_wilderness_isolated_nature_rest", "12", "work_conditions",
       "Wilderness / isolated-nature rest association.",
       "neutral", "WORK_DETAIL", source_reference=REF_H12),
    _h("mars_h12_occupation_associations", "12", "professional_association",
       "Source-described occupation associations include intelligence / scouting, analysis, "
       "trading, investing, and brokerage; not career assignments.",
       "neutral", "WORK_DETAIL", source_reference=REF_H12),
    _h("mars_h12_drive_to_help_suffering_people", "12", "execution",
       "Strong drive to help suffering people.",
       "strength", "WORK_CORE", source_reference=REF_H12),
    _h("mars_h12_samurai_path_service_to_ideal", "12", "execution",
       "“Samurai path” / service to an ideal.",
       "strength", "WORK_CORE", source_reference=REF_H12),
    _h("mars_h12_attraction_to_weapons_strength_sports", "12", "professional_association",
       "Attraction to weapons / strength sports as a source claim; not a hiring or violence claim.",
       "neutral", "WORK_DETAIL", source_reference=REF_H12),
    _h("mars_h12_difficulty_with_direct_active_action", "12", "stuck_blocker",
       "Difficulty with direct active action.",
       "risk", "WORK_CORE", source_reference=REF_H12),
    _h("mars_h12_circumstances_force_concealment_of_intentions", "12", "work_conditions",
       "Circumstances may force concealment of intentions.",
       "risk", "WORK_CORE", source_reference=REF_H12),
    _h("mars_h12_others_may_perceive_as_lazy", "12", "watchout",
       "Others may perceive the person as lazy; not a deterministic identity.",
       "risk", "WORK_CORE", source_reference=REF_H12),
    _h("mars_h12_repeated_clashes_with_existing_order", "12", "conflict",
       "Repeated clashes with existing order.",
       "risk", "WORK_CORE", source_reference=REF_H12),
    _h("mars_h12_timing_sensitivity_acting_against_conditions_fails", "12", "stuck_blocker",
       "Timing sensitivity: acting against conditions can fail.",
       "risk", "WORK_CORE", source_reference=REF_H12),
    _h("mars_h12_source_hidden_violence", "12", "source_specific",
       "Hidden violence source claim; not a violence prediction or accusation.",
       "risk", "SOURCE_ONLY", source_reference=REF_H12),
    _h("mars_h12_affliction_criminal_fraud_activity", "12", "source_specific",
       "Source condition “under affliction”: criminal / fraud activity. Canonical only; "
       "not a legal or hiring allegation. No Mars-affliction resolver is applied.",
       "risk", "SOURCE_ONLY",
       source_reference=REF_H12,
       activation_condition="affliction_unresolved",
       unresolved=True),
)

HOUSE_PACKS: dict[str, tuple[MarsSourceFactDef, ...]] = {
    "1": HOUSE_1_PACK,
    "2": HOUSE_2_PACK,
    "3": HOUSE_3_PACK,
    "4": HOUSE_4_PACK,
    "5": HOUSE_5_PACK,
    "6": HOUSE_6_PACK,
    "7": HOUSE_7_PACK,
    "8": HOUSE_8_PACK,
    "9": HOUSE_9_PACK,
    "10": HOUSE_10_PACK,
    "11": HOUSE_11_PACK,
    "12": HOUSE_12_PACK,
}

SUPPORTED_HOUSE_KEYS: frozenset[str] = frozenset(HOUSE_PACKS)
EXPECTED_HOUSE_SOURCE_REFERENCES: dict[str, str] = {
    "1": REF_H1,
    "2": REF_H2,
    "3": REF_H3,
    "4": REF_H4,
    "5": REF_H5,
    "6": REF_H6,
    "7": REF_H7,
    "8": REF_H8,
    "9": REF_H9,
    "10": REF_H10,
    "11": REF_H11,
    "12": REF_H12,
}
