"""Mercury Source Profile v2 — Sign Batch A1 dual-source packs.

Signs: Aries, Gemini, Cancer
Sources: Lesson 7 Mercury + Bioastrology \"13) Signs of Mercury\"

SOURCE FIRST → SYNTHESIS SECOND.
Two sources are preserved separately via source_reference.
Dual sources on the same sign do NOT create repeated signals by themselves.

Note: SourceFactDef/_f are defined locally to avoid circular import with
mercury_source_knowledge.py (which imports this module).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SourceFactDef:
    id: str
    factor_type: str
    factor_key: str
    category: str
    text: str
    polarity: str
    tags: tuple[str, ...] = ()
    source_reference: str = ""
    activation_condition: str | None = None
    unresolved: bool = False


def _f(
    id: str,
    factor_type: str,
    factor_key: str,
    category: str,
    text: str,
    polarity: str,
    *tags: str,
    source_reference: str,
    activation_condition: str | None = None,
    unresolved: bool = False,
) -> SourceFactDef:
    return SourceFactDef(
        id=id,
        factor_type=factor_type,
        factor_key=factor_key,
        category=category,
        text=text,
        polarity=polarity,
        tags=tags,
        source_reference=source_reference,
        activation_condition=activation_condition,
        unresolved=unresolved,
    )

REF_ARIES_L7 = "lesson7_mercury_aries"
REF_ARIES_BIO = "bioastrology_mercury_aries"
REF_GEMINI_L7 = "lesson7_mercury_gemini"
REF_GEMINI_BIO = "bioastrology_mercury_gemini"
REF_CANCER_L7 = "lesson7_mercury_cancer"
REF_CANCER_BIO = "bioastrology_mercury_cancer"

# ---------------------------------------------------------------------------
# Aries — Lesson 7
# ---------------------------------------------------------------------------
ARIES_LESSON7: tuple[SourceFactDef, ...] = (
    _f("aries_l7_fast_thinking", "sign", "Aries", "thinking",
       "Fast thinking.",
       "neutral", "fast_thinking",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_hurried_thinking", "sign", "Aries", "thinking",
       "Hurried thinking.",
       "risk", "hurried_thinking",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_inattentive_thinking", "sign", "Aries", "thinking",
       "Inattentive thinking.",
       "risk", "inattentive_thinking",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_may_disregard_facts_vs_theory", "sign", "Aries", "thinking",
       "May disregard facts when facts do not fit the native's existing theory.",
       "risk", "disregard_for_facts",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_retains_existing_formulation", "sign", "Aries", "thinking",
       "May retain the existing formulation despite information just heard.",
       "risk", "retains_existing_formulation",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_ready_answer", "sign", "Aries", "thinking",
       "Tends to have a ready answer.",
       "neutral", "ready_answer",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_detects_logic_weak_points", "sign", "Aries", "thinking",
       "Detects weak points in an opponent's logic.",
       "strength", "logic_weakness_detection",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_communication_as_polemics", "sign", "Aries", "communication",
       "Experiences communication intellectually as polemics.",
       "neutral", "polemics",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_perceives_interlocutors_as_opponents", "sign", "Aries", "communication",
       "Tends to perceive interlocutors as opponents.",
       "risk", "opponent_framing",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_ordinary_communication_becomes_argument", "sign", "Aries", "communication",
       "Ordinary communication can become argument.",
       "risk", "argument",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_difficulty_hearing_others", "sign", "Aries", "communication",
       "Difficulty hearing other people.",
       "risk", "listening_difficulty",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_primarily_hears_self", "sign", "Aries", "communication",
       "Primarily hears self.",
       "risk", "listening_difficulty",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_questioner_and_answerer", "sign", "Aries", "communication",
       "Can behave as both questioner and answerer.",
       "neutral", "self_dialoguing",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_repeats_own_position", "sign", "Aries", "communication",
       "Repeats own position.",
       "risk", "repeats_own_position",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_difficult_to_reach_through_dialogue", "sign", "Aries", "communication",
       "Can be difficult to reach through dialogue.",
       "risk", "dialogue_friction", "listening_difficulty",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_mediation_difficult", "sign", "Aries", "communication",
       "Mediation is difficult because communication turns into polemics.",
       "risk", "polemics", "mediation_difficulty",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_dev_slow_down_before_answering", "sign", "Aries", "work_application",
       "Development focus: slow down before answering.",
       "neutral", "slow_down_before_answering",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_dev_verify_facts", "sign", "Aries", "work_application",
       "Development focus: verify facts.",
       "neutral", "verify_facts",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_dev_verify_dates", "sign", "Aries", "work_application",
       "Development focus: verify dates.",
       "neutral", "verify_dates",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_dev_listen_without_interrupting", "sign", "Aries", "work_application",
       "Development focus: listen without interrupting.",
       "neutral", "listen_without_interrupting",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_dev_pause_before_forms", "sign", "Aries", "work_application",
       "Development focus: pause before filling documents/forms.",
       "neutral", "pause_before_forms",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_learn_via_arguing", "sign", "Aries", "learning",
       "Learning support: arguing.",
       "strength", "arguing_learning",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_learn_via_proving", "sign", "Aries", "learning",
       "Learning support: proving.",
       "strength", "proving_learning",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_learn_via_competition", "sign", "Aries", "learning",
       "Learning support: competition.",
       "strength", "competition_learning",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_learn_via_practice", "sign", "Aries", "learning",
       "Learning support: practice.",
       "strength", "practice_based_learning",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_learn_via_immediate_application", "sign", "Aries", "learning",
       "Learning support: immediate real-life application of knowledge.",
       "strength", "immediate_application",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_risk_not_hearing_other_viewpoint", "sign", "Aries", "risk",
       "Learning risk: inability/difficulty hearing another point of view.",
       "risk", "listening_difficulty",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_risk_haste_errors", "sign", "Aries", "risk",
       "Learning risk: haste can produce errors.",
       "risk", "hurried_thinking", "haste_errors",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_env_sees_opponent_in_others", "sign", "Aries", "environment",
       "Sees opponent in other people.",
       "risk", "opponent_framing",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_env_sibling_competitive", "sign", "Aries", "environment",
       "Sibling communication may become competitive.",
       "risk", "sibling_competition",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_env_sibling_argumentative", "sign", "Aries", "environment",
       "Sibling communication may become argumentative.",
       "risk", "sibling_argument",
       source_reference=REF_ARIES_L7),
    _f("aries_l7_env_contacts_impulsive", "sign", "Aries", "environment",
       "Contacts arise impulsively.",
       "neutral", "impulsive_contacts",
       source_reference=REF_ARIES_L7),
)

# ---------------------------------------------------------------------------
# Aries — Bioastrology (beyond Lesson 7; keep related-but-distinct)
# ---------------------------------------------------------------------------
ARIES_BIOASTROLOGY: tuple[SourceFactDef, ...] = (
    _f("aries_bio_martian_speed_coloring", "sign", "Aries", "thinking",
       "Thinking, communication and learning are colored by Martian speed.",
       "neutral", "martian_speed",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_technical_practicality", "sign", "Aries", "thinking",
       "Thinking/learning have technical practicality.",
       "strength", "technical_practicality",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_strong_through_speed_not_endurance", "sign", "Aries", "thinking",
       "Thinking is strong through SPEED rather than endurance.",
       "neutral", "speed_over_endurance",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_strong_through_speed_not_depth", "sign", "Aries", "thinking",
       "Thinking is strong through SPEED rather than depth.",
       "neutral", "speed_over_depth",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_ability_to_argue", "sign", "Aries", "communication",
       "Ability/tendency to argue.",
       "strength", "argue",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_vocal_ability", "sign", "Aries", "communication",
       "Vocal ability/potential.",
       "strength", "vocal_ability",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_oratory_ability", "sign", "Aries", "communication",
       "Oratory ability/potential.",
       "strength", "oratory",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_engineering_ability", "sign", "Aries", "work_application",
       "Engineering ability/potential (source-described tendency).",
       "strength", "engineering_ability",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_legal_ability", "sign", "Aries", "work_application",
       "Legal ability/potential (source-described tendency).",
       "strength", "legal_ability",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_sales_ability", "sign", "Aries", "work_application",
       "Sales ability/potential (source-described tendency).",
       "strength", "sales",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_monologue_communication", "sign", "Aries", "communication",
       "Tends to communicate in monologues.",
       "risk", "monologue_communication",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_tends_not_to_hear_others", "sign", "Aries", "communication",
       "Tends not to hear other people.",
       "risk", "listening_difficulty",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_learns_through_practical_implementation", "sign", "Aries", "learning",
       "Learns well through practical implementation.",
       "strength", "practice_based_learning",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_learns_through_trial_and_error", "sign", "Aries", "learning",
       "Learns through trial-and-error / \"method of poking\".",
       "strength", "trial_and_error_learning",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_learns_through_disputes", "sign", "Aries", "learning",
       "Learns through disputes.",
       "strength", "dispute_learning",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_motivation_challenge", "sign", "Aries", "learning",
       "Learning motivation: challenge.",
       "neutral", "challenge_motivated_learning",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_motivation_obstacle", "sign", "Aries", "learning",
       "Learning motivation: obstacle.",
       "neutral", "obstacle_motivated_learning",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_motivation_contest_challenge", "sign", "Aries", "learning",
       "Learning motivation: being challenged to a fight/contest.",
       "neutral", "contest_challenge_motivated_learning",
       source_reference=REF_ARIES_BIO),
    _f("aries_bio_source_sexual_motivation_wording", "sign", "Aries", "source_specific",
       "Source framework also includes sexual motivation wording for learning drive; preserved as source wording only, not a professional/hiring recommendation.",
       "neutral", "source_sexual_motivation_wording",
       source_reference=REF_ARIES_BIO),
)

ARIES_ALL: tuple[SourceFactDef, ...] = ARIES_LESSON7 + ARIES_BIOASTROLOGY

# ---------------------------------------------------------------------------
# Gemini — Lesson 7
# ---------------------------------------------------------------------------
GEMINI_LESSON7: tuple[SourceFactDef, ...] = (
    _f("gemini_l7_logical_thinking", "sign", "Gemini", "thinking",
       "Logical thinking.",
       "strength", "logical_thinking",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_highly_contact_oriented_thinking", "sign", "Gemini", "thinking",
       "Highly contact-oriented thinking.",
       "strength", "contact_oriented_thinking",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_quantity_may_dominate_quality", "sign", "Gemini", "thinking",
       "Quantity of information may dominate quality.",
       "risk", "information_quantity_bias",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_high_working_memory_speed", "sign", "Gemini", "thinking",
       "Very high operational / working-memory speed.",
       "strength", "working_memory_speed",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_particular_to_general", "sign", "Gemini", "thinking",
       "Thinking goes from particular to general.",
       "neutral", "bottom_up_thinking",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_may_fail_to_see_whole", "sign", "Gemini", "thinking",
       "May fail to see the whole picture.",
       "risk", "big_picture_risk",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_learns_easily_in_dialogue", "sign", "Gemini", "learning",
       "Learns easily in dialogue.",
       "strength", "dialogue_learning",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_strong_commercial_ability", "sign", "Gemini", "work_application",
       "Strong commercial ability.",
       "strength", "commercial_ability",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_strong_negotiation_ability", "sign", "Gemini", "work_application",
       "Strong negotiation ability.",
       "strength", "negotiation",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_simplifies_abstractions", "sign", "Gemini", "communication",
       "Communicates high abstractions in simple language.",
       "strength", "simplifying_abstractions",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_group_listening", "sign", "Gemini", "communication",
       "Can hear/track each person while working with a large group.",
       "strength", "group_listening",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_dev_prioritize_information", "sign", "Gemini", "work_application",
       "Development focus: prioritize information.",
       "neutral", "information_prioritization",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_dev_slow_down", "sign", "Gemini", "work_application",
       "Development focus: slow down.",
       "neutral", "slow_down",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_dev_focus_one_subject", "sign", "Gemini", "work_application",
       "Development focus: focus on one subject.",
       "neutral", "single_subject_focus",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_dev_avoid_scattering", "sign", "Gemini", "work_application",
       "Development focus: avoid scattering across parallel tasks.",
       "neutral", "avoid_scattering",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_support_lectures", "sign", "Gemini", "learning",
       "Learning support: lectures.",
       "neutral", "lecture_learning",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_support_books", "sign", "Gemini", "learning",
       "Learning support: books.",
       "neutral", "book_learning",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_support_groups", "sign", "Gemini", "learning",
       "Learning support: groups.",
       "neutral", "group_learning",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_support_teachers", "sign", "Gemini", "learning",
       "Learning support: teachers.",
       "neutral", "teacher_learning",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_support_multi_person_communication", "sign", "Gemini", "learning",
       "Learning support: communication with multiple people.",
       "neutral", "multi_person_communication_learning",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_risk_boredom_prolonged_one_subject", "sign", "Gemini", "risk",
       "Learning risk: boredom with prolonged work on one subject.",
       "risk", "boredom_with_one_subject",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_understands_quickly", "sign", "Gemini", "learning",
       "Understands quickly.",
       "strength", "quick_understanding",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_quick_understanding_may_cause_laziness", "sign", "Gemini", "risk",
       "Quick understanding may contribute to laziness.",
       "risk", "quick_understanding_laziness",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_quick_understanding_may_lose_interest", "sign", "Gemini", "risk",
       "Quick understanding may contribute to loss of interest.",
       "risk", "quick_understanding_loss_of_interest",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_env_indiscriminate_acquaintances", "sign", "Gemini", "environment",
       "Indiscriminate / omnivorous acquaintances.",
       "neutral", "omnivorous_contacts",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_env_constantly_renews", "sign", "Gemini", "environment",
       "Environment constantly renews.",
       "neutral", "renewing_environment",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_env_sibling_easy", "sign", "Gemini", "environment",
       "Sibling relations may be easy.",
       "neutral", "sibling_ease",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_env_sibling_superficial", "sign", "Gemini", "environment",
       "Sibling relations may be superficial.",
       "risk", "sibling_superficiality",
       source_reference=REF_GEMINI_L7),
    _f("gemini_l7_env_contact_quantity_over_quality", "sign", "Gemini", "environment",
       "Quantity of contacts may dominate quality.",
       "risk", "contact_quantity_bias",
       source_reference=REF_GEMINI_L7),
)

# ---------------------------------------------------------------------------
# Gemini — Bioastrology
# ---------------------------------------------------------------------------
GEMINI_BIOASTROLOGY: tuple[SourceFactDef, ...] = (
    _f("gemini_bio_major_domicile_sync", "sign", "Gemini", "source_specific",
       "Major domicile: strong synchronization between Mercury functions and Gemini sign environment (source status statement; not a numerical score).",
       "neutral", "major_domicile_sync",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_extraordinary_speed", "sign", "Gemini", "thinking",
       "Extraordinary speed of thinking/communication/learning.",
       "strength", "extraordinary_speed",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_informational_omnivorousness", "sign", "Gemini", "thinking",
       "Informational omnivorousness.",
       "neutral", "informational_omnivorousness",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_slight_technical_orientation", "sign", "Gemini", "thinking",
       "Slight technical orientation/tendency.",
       "neutral", "technical_orientation",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_intellectual_multitasking", "sign", "Gemini", "thinking",
       "Intellectual multitasking.",
       "strength", "intellectual_multitasking",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_rationalism", "sign", "Gemini", "thinking",
       "Rationalism.",
       "strength", "rationalism",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_reliance_on_facts", "sign", "Gemini", "thinking",
       "Reliance on facts.",
       "strength", "fact_reliance",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_strong_memory", "sign", "Gemini", "memory",
       "Strong memory.",
       "strength", "strong_memory",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_salesperson_ability", "sign", "Gemini", "work_application",
       "Salesperson ability (source-described tendency).",
       "strength", "sales",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_communicator_ability", "sign", "Gemini", "communication",
       "Communicator ability (source-described tendency).",
       "strength", "communicator_ability",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_writing_talent", "sign", "Gemini", "work_application",
       "Writing talent/potential (source-described tendency).",
       "strength", "writing",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_oratory_talent", "sign", "Gemini", "communication",
       "Oratory talent/potential (source-described tendency).",
       "strength", "oratory",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_driving_ability", "sign", "Gemini", "work_application",
       "Driving ability/potential (source-described tendency).",
       "strength", "driving",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_foreign_language_polyglot", "sign", "Gemini", "learning",
       "Foreign-language / polyglot potential (source-described tendency).",
       "strength", "foreign_languages",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_learns_from_many_sources", "sign", "Gemini", "learning",
       "Learns from many / essentially any kinds of sources.",
       "strength", "omnivorous_learning",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_strong_student_potential", "sign", "Gemini", "learning",
       "Strong student potential.",
       "strength", "student_potential",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_demonstrative_teacher_potential", "sign", "Gemini", "learning",
       "Demonstrative-teacher potential.",
       "strength", "teaching",
       source_reference=REF_GEMINI_BIO),
    _f("gemini_bio_curiosity_motivated_learning", "sign", "Gemini", "learning",
       "Learning motivation may arise from basic curiosity without needing an external incentive.",
       "neutral", "curiosity_motivated_learning",
       source_reference=REF_GEMINI_BIO),
)

GEMINI_AFFLICTED: tuple[SourceFactDef, ...] = (
    _f("gemini_bio_afflicted_lying", "sign", "Gemini", "risk",
       "Source affliction tendency (activated via project hard_aspected proxy for 'при поражении'): lying (source-described tendency, not a person accusation).",
       "risk", "lying_distortion",
       source_reference=REF_GEMINI_BIO, activation_condition="hard_aspected"),
    _f("gemini_bio_afflicted_excessive_verbal_output", "sign", "Gemini", "risk",
       "Source affliction tendency (activated via project hard_aspected proxy for 'при поражении'): excessive verbal output / verbal diarrhea.",
       "risk", "excessive_verbal_output",
       source_reference=REF_GEMINI_BIO, activation_condition="hard_aspected"),
    _f("gemini_bio_afflicted_words_exceed_actions", "sign", "Gemini", "risk",
       "Source affliction tendency (activated via project hard_aspected proxy for 'при поражении'): quantity of words may greatly exceed quantity of actions.",
       "risk", "words_exceed_actions",
       source_reference=REF_GEMINI_BIO, activation_condition="hard_aspected"),
)

GEMINI_ALL: tuple[SourceFactDef, ...] = GEMINI_LESSON7 + GEMINI_BIOASTROLOGY + GEMINI_AFFLICTED

# ---------------------------------------------------------------------------
# Cancer — Lesson 7
# ---------------------------------------------------------------------------
CANCER_LESSON7: tuple[SourceFactDef, ...] = (
    _f("cancer_l7_mind_attached_to_past", "sign", "Cancer", "thinking",
       "Mind attached to the past.",
       "neutral", "past_oriented_thinking",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_searches_for_roots", "sign", "Cancer", "thinking",
       "Searches for roots/origin of an idea.",
       "strength", "origin_search",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_excellent_imagination", "sign", "Cancer", "thinking",
       "Excellent imagination.",
       "strength", "imagination",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_deep_associative_connections", "sign", "Cancer", "thinking",
       "Senses deep associative connections.",
       "strength", "associative_thinking",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_arguments_arise_intuitively", "sign", "Cancer", "thinking",
       "Arguments arise intuitively.",
       "neutral", "intuitive_argumentation",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_intuitive_args_hard_to_explain", "sign", "Cancer", "communication",
       "Intuitive arguments can be hard to explain.",
       "risk", "intuitive_argumentation", "verbal_expression_difficulty",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_thought_hard_to_express", "sign", "Cancer", "communication",
       "Thought can be difficult to express verbally.",
       "risk", "verbal_expression_difficulty",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_speech_can_become_tangled", "sign", "Cancer", "communication",
       "Speech/expression can become tangled.",
       "risk", "tangled_speech", "verbal_expression_difficulty",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_speech_expresses_emotion", "sign", "Cancer", "communication",
       "Primary function of speech is expressing emotion.",
       "neutral", "emotional_communication",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_viewpoint_depends_on_tastes", "sign", "Cancer", "thinking",
       "Viewpoint depends on tastes/views/habits.",
       "neutral", "viewpoint_taste_habit_dependence",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_need_emotional_feedback", "sign", "Cancer", "communication",
       "Strong need for emotional feedback.",
       "neutral", "emotional_feedback_need",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_good_improvisation", "sign", "Cancer", "communication",
       "Good improvisation.",
       "strength", "improvisation",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_sensitivity_to_dialogue_atmosphere", "sign", "Cancer", "communication",
       "Sensitivity to dialogue atmosphere.",
       "neutral", "dialogue_atmosphere_sensitivity",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_dev_subjectivity_risk", "sign", "Cancer", "risk",
       "Development note: subjectivity risk.",
       "risk", "subjectivity_risk",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_dev_separate_emotion_from_argument", "sign", "Cancer", "work_application",
       "Development focus: need to separate emotion from rational argument.",
       "neutral", "separate_emotion_from_argument",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_dev_structured_speech_training", "sign", "Cancer", "work_application",
       "Development focus: structured-speech training.",
       "neutral", "structured_speech_training",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_dev_avoid_stuck_in_details", "sign", "Cancer", "work_application",
       "Development focus: avoid getting stuck in details.",
       "neutral", "avoid_detail_fixation",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_dev_retain_central_idea", "sign", "Cancer", "work_application",
       "Development focus: retain central idea.",
       "neutral", "retain_central_idea",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_learn_comfortable_environment", "sign", "Cancer", "learning",
       "Learning support: comfortable/soft environment.",
       "neutral", "comfortable_learning_environment",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_learn_small_segments", "sign", "Cancer", "learning",
       "Learning support: divide information into small pieces/segments.",
       "neutral", "segmented_learning",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_sticky_memory_emotions", "sign", "Cancer", "memory",
       "Sticky memory for emotions.",
       "strength", "emotion_memory",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_sticky_memory_images", "sign", "Cancer", "memory",
       "Sticky memory for images.",
       "strength", "image_memory",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_sticky_memory_smells", "sign", "Cancer", "memory",
       "Sticky memory for smells.",
       "strength", "smell_memory",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_learning_through_authorities", "sign", "Cancer", "learning",
       "Learning through authorities.",
       "neutral", "authority_learning",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_learning_through_traditions", "sign", "Cancer", "learning",
       "Learning through traditions.",
       "neutral", "tradition_learning",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_risk_emotionality_interferes_learning", "sign", "Cancer", "risk",
       "Emotionality can interfere with learning.",
       "risk", "emotionality_interferes_learning",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_risk_mental_drifting", "sign", "Cancer", "risk",
       "Mental drifting.",
       "risk", "mental_drifting",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_risk_difficulty_concentrating", "sign", "Cancer", "risk",
       "Difficulty concentrating.",
       "risk", "concentration_difficulty",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_env_narrow_pleasant_circle", "sign", "Cancer", "environment",
       "Narrow circle of people the native finds pleasant.",
       "neutral", "narrow_pleasant_circle",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_env_authorities_important", "sign", "Cancer", "environment",
       "Authorities are important in environment.",
       "neutral", "authority_environment",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_env_traditions_important", "sign", "Cancer", "environment",
       "Traditions are important in environment.",
       "neutral", "tradition_environment",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_env_emotional_attachment_siblings", "sign", "Cancer", "environment",
       "Emotional attachment to siblings.",
       "neutral", "sibling_emotional_attachment",
       source_reference=REF_CANCER_L7),
    _f("cancer_l7_env_possible_social_withdrawal", "sign", "Cancer", "environment",
       "Possible social withdrawal related to sensitivity/vulnerability.",
       "risk", "social_withdrawal_sensitivity",
       source_reference=REF_CANCER_L7),
)

# ---------------------------------------------------------------------------
# Cancer — Bioastrology
# ---------------------------------------------------------------------------
CANCER_BIOASTROLOGY: tuple[SourceFactDef, ...] = (
    _f("cancer_bio_thinking_colored_by_emotionality", "sign", "Cancer", "thinking",
       "Thinking is colored by Cancer emotionality.",
       "neutral", "emotional_coloring",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_communication_colored_by_emotionality", "sign", "Cancer", "communication",
       "Communication is colored by Cancer emotionality.",
       "neutral", "emotional_coloring",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_learning_colored_by_emotionality", "sign", "Cancer", "learning",
       "Learning is colored by Cancer emotionality.",
       "neutral", "emotional_coloring",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_depth_substantive_nature", "sign", "Cancer", "thinking",
       "Depth / substantive nature.",
       "strength", "depth",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_depends_on_moon_sign", "sign", "Cancer", "source_specific",
       "Source dependency: manifestation depends strongly on Moon sign (range from home-oriented quiet expression to public speaking). No Moon-sign resolver is applied in this prototype.",
       "conditional", "moon_sign_dependency",
       source_reference=REF_CANCER_BIO, unresolved=True),
    _f("cancer_bio_image_based_emotional_memory", "sign", "Cancer", "memory",
       "Image-based emotional memory.",
       "strength", "image_based_emotional_memory",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_humanities_aptitude", "sign", "Cancer", "work_application",
       "Humanities aptitude/potential (source-described tendency).",
       "strength", "humanities_aptitude",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_emotional_intelligence_source_claim", "sign", "Cancer", "source_specific",
       "Emotional-intelligence potential as an explicit source claim; not treated as a scientifically measured or certified professional ability.",
       "neutral", "emotional_intelligence_source_claim",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_storyteller_talent", "sign", "Cancer", "communication",
       "Storyteller talent/potential (source-described tendency).",
       "strength", "storytelling",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_writer_association", "sign", "Cancer", "work_application",
       "Writer association/potential (source-described tendency).",
       "strength", "writing",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_speech_may_be_unstable", "sign", "Cancer", "communication",
       "Speech may be unstable.",
       "risk", "unstable_speech",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_can_be_knocked_off_balance_in_speech", "sign", "Cancer", "communication",
       "Can be knocked off balance/confused in speech.",
       "risk", "speech_easily_disrupted",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_can_be_hurt_in_communication", "sign", "Cancer", "communication",
       "Can be hurt/offended in communication.",
       "risk", "communication_hurt_sensitivity",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_may_lose_debates_lacking_force", "sign", "Cancer", "communication",
       "May lose debates because forceful pressure is lacking.",
       "risk", "debate_pressure_deficit",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_psychologically_dissect_texts", "sign", "Cancer", "thinking",
       "Ability to psychologically dissect texts.",
       "strength", "text_psychological_dissection",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_notice_subtext", "sign", "Cancer", "thinking",
       "Ability to notice subtext.",
       "strength", "text_subtext_detection",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_notice_rhyme", "sign", "Cancer", "thinking",
       "Ability to notice rhyme.",
       "strength", "rhyme_detection",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_see_hidden_meaning", "sign", "Cancer", "thinking",
       "Ability to see hidden meaning.",
       "strength", "hidden_meaning_detection",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_living_image_in_web_of_facts", "sign", "Cancer", "thinking",
       "Ability to perceive a living image embedded in a web of facts.",
       "strength", "living_image_in_facts",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_attachment_to_classics_opinions", "sign", "Cancer", "learning",
       "Attachment to opinions of classics.",
       "neutral", "classics_opinion_attachment",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_attachment_to_parents_opinions", "sign", "Cancer", "learning",
       "Attachment to parents' opinions.",
       "neutral", "parental_opinion_attachment",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_learns_through_impressions", "sign", "Cancer", "learning",
       "Learns well through impressions.",
       "strength", "impression_learning",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_learns_through_video", "sign", "Cancer", "learning",
       "Learns well through video.",
       "strength", "video_learning",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_learns_through_audio", "sign", "Cancer", "learning",
       "Learns well through audio.",
       "strength", "audio_learning",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_learns_through_lectures", "sign", "Cancer", "learning",
       "Learns well through lectures.",
       "strength", "lecture_learning",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_learns_around_familiar_people", "sign", "Cancer", "learning",
       "Learns well around familiar / close people.",
       "strength", "familiar_group_learning",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_also_accepts_books", "sign", "Cancer", "learning",
       "Also accepts books as a learning source.",
       "neutral", "book_learning",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_motivation_comfortable_environment", "sign", "Cancer", "learning",
       "Learning motivation: comfortable environment.",
       "neutral", "comfortable_learning_environment",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_motivation_favorite_teacher", "sign", "Cancer", "learning",
       "Learning motivation: connection of facts to a favorite/respected teacher.",
       "neutral", "teacher_motivated_learning",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_motivation_tradition", "sign", "Cancer", "learning",
       "Learning motivation: tradition.",
       "neutral", "tradition_learning",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_motivation_familiar_group", "sign", "Cancer", "learning",
       "Learning motivation: native/familiar group.",
       "neutral", "familiar_group_learning",
       source_reference=REF_CANCER_BIO),
    _f("cancer_bio_motivation_strong_emotion", "sign", "Cancer", "learning",
       "Learning motivation: strong emotion.",
       "neutral", "emotion_motivated_learning",
       source_reference=REF_CANCER_BIO),
)

CANCER_AFFLICTED: tuple[SourceFactDef, ...] = (
    _f("cancer_bio_afflicted_scatter_distractibility", "sign", "Cancer", "risk",
       "Source affliction tendency (activated via project hard_aspected proxy for 'при поражении'): scatter / distractibility.",
       "risk", "distractibility",
       source_reference=REF_CANCER_BIO, activation_condition="hard_aspected"),
    _f("cancer_bio_afflicted_loss_of_focus", "sign", "Cancer", "risk",
       "Source affliction tendency (activated via project hard_aspected proxy for 'при поражении'): loss of focus.",
       "risk", "loss_of_focus",
       source_reference=REF_CANCER_BIO, activation_condition="hard_aspected"),
    _f("cancer_bio_afflicted_losing_the_thread", "sign", "Cancer", "risk",
       "Source affliction tendency (activated via project hard_aspected proxy for 'при поражении'): losing the thread.",
       "risk", "losing_the_thread",
       source_reference=REF_CANCER_BIO, activation_condition="hard_aspected"),
    _f("cancer_bio_afflicted_losing_central_meaning", "sign", "Cancer", "risk",
       "Source affliction tendency (activated via project hard_aspected proxy for 'при поражении'): losing the central meaning.",
       "risk", "losing_central_meaning",
       source_reference=REF_CANCER_BIO, activation_condition="hard_aspected"),
    _f("cancer_bio_afflicted_everyday_momentary_thinking", "sign", "Cancer", "risk",
       "Source affliction tendency (activated via project hard_aspected proxy for 'при поражении'): everyday momentary thinking.",
       "risk", "momentary_thinking",
       source_reference=REF_CANCER_BIO, activation_condition="hard_aspected"),
    _f("cancer_bio_afflicted_thinking_trapped_by_habits", "sign", "Cancer", "risk",
       "Source affliction tendency (activated via project hard_aspected proxy for 'при поражении'): thinking trapped by habits.",
       "risk", "habit_bound_thinking",
       source_reference=REF_CANCER_BIO, activation_condition="hard_aspected"),
    _f("cancer_bio_afflicted_thinking_trapped_by_outdated_beliefs", "sign", "Cancer", "risk",
       "Source affliction tendency (activated via project hard_aspected proxy for 'при поражении'): thinking trapped by outdated beliefs.",
       "risk", "outdated_belief_bound_thinking",
       source_reference=REF_CANCER_BIO, activation_condition="hard_aspected"),
    _f("cancer_bio_afflicted_disregard_for_facts", "sign", "Cancer", "risk",
       "Source affliction tendency (activated via project hard_aspected proxy for 'при поражении'): disregard for facts.",
       "risk", "disregard_for_facts",
       source_reference=REF_CANCER_BIO, activation_condition="hard_aspected"),
    _f("cancer_bio_afflicted_habit_bound_momentary_reasoning", "sign", "Cancer", "risk",
       "Source affliction tendency (activated via project hard_aspected proxy for 'при поражении'): habit-bound momentary reasoning.",
       "risk", "habit_bound_momentary_reasoning",
       source_reference=REF_CANCER_BIO, activation_condition="hard_aspected"),
)

CANCER_ALL: tuple[SourceFactDef, ...] = CANCER_LESSON7 + CANCER_BIOASTROLOGY + CANCER_AFFLICTED

A1_SIGN_PACKS: tuple[SourceFactDef, ...] = ARIES_ALL + GEMINI_ALL + CANCER_ALL
