"""Mercury Source Profile v2 — Sign Batch A3 dual-source packs.

Signs: Capricorn, Aquarius, Pisces
Sources: Lesson 7 Mercury + Bioastrology \"Знаки Меркурия\"

SOURCE FIRST → SYNTHESIS SECOND.
Dual sources on the same sign do NOT create repeated signals by themselves.

Local SourceFactDef/_f avoid circular import with mercury_source_knowledge.py.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SourceFactDef:
    id: str
    factor_type: str
    factor_key: str
    category: str
    text: str
    polarity: str
    tags: tuple[str, ...] = ()
    source_reference: str = ""
    activation_condition: str | None = None
    unresolved: bool = False


def _f(
    id: str,
    factor_type: str,
    factor_key: str,
    category: str,
    text: str,
    polarity: str,
    *tags: str,
    source_reference: str,
    activation_condition: str | None = None,
    unresolved: bool = False,
) -> SourceFactDef:
    return SourceFactDef(
        id=id,
        factor_type=factor_type,
        factor_key=factor_key,
        category=category,
        text=text,
        polarity=polarity,
        tags=tags,
        source_reference=source_reference,
        activation_condition=activation_condition,
        unresolved=unresolved,
    )


REF_CAPRICORN_L7 = "lesson7_mercury_capricorn"
REF_CAPRICORN_BIO = "bioastrology_mercury_capricorn"
REF_AQUARIUS_L7 = "lesson7_mercury_aquarius"
REF_AQUARIUS_BIO = "bioastrology_mercury_aquarius"
REF_PISCES_L7 = "lesson7_mercury_pisces"
REF_PISCES_BIO = "bioastrology_mercury_pisces"

_AFFLICTED_PREFIX = (
    "Source affliction tendency (activated via project hard_aspected proxy "
    "for 'при поражении'): "
)

# ---------------------------------------------------------------------------
# Capricorn — Lesson 7
# ---------------------------------------------------------------------------
CAPRICORN_LESSON7: tuple[SourceFactDef, ...] = (
    _f("capricorn_l7_structured_thinking", "sign", "Capricorn", "thinking",
       "Thinking is clearly structured.",
       "strength", "structured_thinking",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_concrete_thinking", "sign", "Capricorn", "thinking",
       "Concrete thinking.",
       "strength", "concrete_thinking",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_businesslike_thinking", "sign", "Capricorn", "thinking",
       "Businesslike thinking.",
       "strength", "businesslike_thinking",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_scientific_mindset", "sign", "Capricorn", "thinking",
       "Scientific mindset.",
       "strength", "scientific_mindset",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_iron_logic", "sign", "Capricorn", "thinking",
       "Strong / \"iron\" logic.",
       "strength", "iron_logic",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_chopped_concise_phrases", "sign", "Capricorn", "communication",
       "Phrases are chopped / concise.",
       "neutral", "chopped_concise_phrases",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_speech_without_filler", "sign", "Capricorn", "communication",
       "Speech is without unnecessary filler.",
       "neutral", "speech_without_filler",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_focus_on_essence", "sign", "Capricorn", "thinking",
       "Focuses on essence.",
       "strength", "focus_on_essence",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_focus_on_principle", "sign", "Capricorn", "thinking",
       "Focuses on principle.",
       "strength", "focus_on_principle",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_one_thing_at_a_time", "sign", "Capricorn", "thinking",
       "Tends to do one thing at a time.",
       "neutral", "one_thing_at_a_time",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_one_thought_at_a_time", "sign", "Capricorn", "thinking",
       "Tends to hold one thought at a time.",
       "neutral", "one_thought_at_a_time",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_formal_communication", "sign", "Capricorn", "communication",
       "Formal communication style.",
       "neutral", "formal_communication",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_limited_contact", "sign", "Capricorn", "communication",
       "Limited contact / restrained sociability.",
       "neutral", "limited_contact",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_quiet_speech", "sign", "Capricorn", "communication",
       "Quiet speech.",
       "neutral", "quiet_speech",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_calm_speech", "sign", "Capricorn", "communication",
       "Calm speech.",
       "neutral", "calm_speech",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_beautiful_voice", "sign", "Capricorn", "communication",
       "Source describes a beautiful voice.",
       "neutral", "beautiful_voice",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_strong_critic", "sign", "Capricorn", "communication",
       "Strong critic.",
       "strength", "strong_critic",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_common_sense_reliance", "sign", "Capricorn", "thinking",
       "Relies on common sense.",
       "neutral", "common_sense_reliance",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_authoritative_opinion_reliance", "sign", "Capricorn", "thinking",
       "Relies on tested / authoritative opinions.",
       "neutral", "authoritative_opinion_reliance",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_lack_of_haste", "sign", "Capricorn", "communication",
       "Lack of haste.",
       "neutral", "lack_of_haste",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_rely_on_proven_experience", "sign", "Capricorn", "work_application",
       "Development focus: rely on proven experience.",
       "neutral", "proven_experience",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_develop_fundamentality", "sign", "Capricorn", "work_application",
       "Development focus: develop fundamentality.",
       "neutral", "fundamentality",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_systematize", "sign", "Capricorn", "work_application",
       "Development focus: systematize.",
       "neutral", "systematize",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_sarcasm_when_imagination_lacking", "sign", "Capricorn", "source_specific",
       "Source specifically suggests sarcasm as a humor form when imagination is lacking.",
       "neutral", "sarcasm_humor_when_imagination_lacking",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_needs_why_material_learned", "sign", "Capricorn", "learning",
       "Needs to understand why the material is being learned.",
       "neutral", "why_learning_needed",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_needs_sequence_of_actions", "sign", "Capricorn", "learning",
       "Needs sequence of actions.",
       "neutral", "sequence_of_actions",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_systems_help", "sign", "Capricorn", "learning",
       "Systems help learning.",
       "neutral", "systems_learning",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_tables_help", "sign", "Capricorn", "learning",
       "Tables help learning.",
       "neutral", "table_learning",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_schedules_help", "sign", "Capricorn", "learning",
       "Schedules help learning.",
       "neutral", "schedule_learning",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_plans_help", "sign", "Capricorn", "learning",
       "Plans help learning.",
       "neutral", "plan_learning",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_structure_helps", "sign", "Capricorn", "learning",
       "Structure helps learning.",
       "neutral", "structure_learning",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_notes_help", "sign", "Capricorn", "learning",
       "Notes help learning.",
       "neutral", "notes_learning",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_algorithms_help", "sign", "Capricorn", "learning",
       "Algorithms help learning.",
       "neutral", "algorithm_learning",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_schemes_help", "sign", "Capricorn", "learning",
       "Schemes help learning.",
       "neutral", "scheme_learning",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_metrics_help", "sign", "Capricorn", "learning",
       "Clear indicators / metrics help learning.",
       "neutral", "metrics_learning",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_slow_deliberate_perception", "sign", "Capricorn", "learning",
       "Information perception is slow / deliberate.",
       "neutral", "slow_deliberate_perception",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_stubbornness_in_views", "sign", "Capricorn", "risk",
       "Difficulty: stubbornness in views.",
       "risk", "stubbornness_in_views",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_env_formal_communication", "sign", "Capricorn", "environment",
       "Formal communication style in the close environment.",
       "neutral", "env_formal_communication",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_env_limited_contact", "sign", "Capricorn", "environment",
       "Limited contact in the close environment.",
       "neutral", "env_limited_contact",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_env_businesslike_siblings", "sign", "Capricorn", "environment",
       "Businesslike sibling relationships.",
       "neutral", "businesslike_sibling_relationships",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_env_concrete_without_water", "sign", "Capricorn", "environment",
       "Sibling/environment communication \"without water\", concrete.",
       "neutral", "concrete_sibling_communication",
       source_reference=REF_CAPRICORN_L7),
    _f("capricorn_l7_env_usefulness_selected", "sign", "Capricorn", "environment",
       "Social environment selected partly by usefulness.",
       "neutral", "usefulness_selected_environment",
       source_reference=REF_CAPRICORN_L7),
)

CAPRICORN_BIOASTROLOGY: tuple[SourceFactDef, ...] = (
    _f("capricorn_bio_clear_thinking_communication_learning", "sign", "Capricorn", "thinking",
       "Thinking/communication/learning described as clear.",
       "strength", "clear_thinking_communication_learning",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_structured", "sign", "Capricorn", "thinking",
       "Structured thinking/communication/learning.",
       "strength", "structured_thinking",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_logical_thinking", "sign", "Capricorn", "thinking",
       "Logical thinking.",
       "strength", "logical_thinking",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_table_template_oriented", "sign", "Capricorn", "thinking",
       "Table/template oriented.",
       "strength", "table_template_oriented",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_technical_aptitude", "sign", "Capricorn", "work_application",
       "Technical aptitude (source-described tendency).",
       "strength", "technical_ability",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_logic", "sign", "Capricorn", "thinking",
       "Logic.",
       "strength", "logic",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_memory", "sign", "Capricorn", "memory",
       "Memory.",
       "strength", "memory_aptitude",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_iron_argumentation", "sign", "Capricorn", "communication",
       "Strong / \"iron\" argumentation in disputes.",
       "strength", "iron_argumentation",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_planning", "sign", "Capricorn", "thinking",
       "Planning.",
       "strength", "planning",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_forecasting", "sign", "Capricorn", "thinking",
       "Forecasting.",
       "strength", "forecasting",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_occupation_associations", "sign", "Capricorn", "source_specific",
       "Source-described occupation associations: often found among leaders, scientists, and entrepreneurs; not career assignments.",
       "neutral", "occupation_associations",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_difficult_casual_chat", "sign", "Capricorn", "communication",
       "Difficult to chat casually / \"about life\".",
       "risk", "difficult_casual_chat",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_needs_practical_usefulness_for_communication", "sign", "Capricorn", "communication",
       "Difficult to communicate when there is no practical/business usefulness.",
       "risk", "needs_practical_usefulness_for_communication",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_calm_voice", "sign", "Capricorn", "communication",
       "Voice generally calm.",
       "neutral", "calm_voice",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_commanding_tone", "sign", "Capricorn", "communication",
       "Source describes commanding tone.",
       "neutral", "commanding_tone",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_sober_cold_style", "sign", "Capricorn", "communication",
       "Sober/cold style.",
       "neutral", "sober_cold_style",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_unemotional_style", "sign", "Capricorn", "communication",
       "Unemotional style.",
       "neutral", "unemotional_style",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_learning_own_experience", "sign", "Capricorn", "learning",
       "Learning through own experience.",
       "strength", "own_experience_learning",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_learning_practice", "sign", "Capricorn", "learning",
       "Learning through practice.",
       "strength", "practice_based_learning",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_learning_alone", "sign", "Capricorn", "learning",
       "Learning alone.",
       "strength", "alone_learning",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_learning_official_institutions", "sign", "Capricorn", "learning",
       "Learning through official educational institutions.",
       "neutral", "official_institution_learning",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_learning_long_systematic_courses", "sign", "Capricorn", "learning",
       "Learning through long systematic courses.",
       "neutral", "long_systematic_course_learning",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_diploma_certificate_matters", "sign", "Capricorn", "learning",
       "Diploma/certificate completion matters.",
       "neutral", "diploma_certificate_completion",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_motivation_build_structure", "sign", "Capricorn", "learning",
       "Learning motivation: build structure.",
       "neutral", "structure_building_motivation",
       source_reference=REF_CAPRICORN_BIO),
    _f("capricorn_bio_motivation_logical_interconnections", "sign", "Capricorn", "learning",
       "Learning motivation: build logical interconnections.",
       "neutral", "logical_interconnection_motivation",
       source_reference=REF_CAPRICORN_BIO),
)

CAPRICORN_AFFLICTED: tuple[SourceFactDef, ...] = (
    _f("capricorn_bio_afflicted_closedness", "sign", "Capricorn", "risk",
       _AFFLICTED_PREFIX + "closedness.",
       "risk", "closedness",
       source_reference=REF_CAPRICORN_BIO, activation_condition="hard_aspected"),
    _f("capricorn_bio_afflicted_unsociability", "sign", "Capricorn", "risk",
       _AFFLICTED_PREFIX + "unsociability.",
       "risk", "unsociability",
       source_reference=REF_CAPRICORN_BIO, activation_condition="hard_aspected"),
    _f("capricorn_bio_afflicted_professional_vs_everyday_orientation", "sign", "Capricorn", "risk",
       _AFFLICTED_PREFIX
       + "professional-domain knowledge can coexist with poor orientation in other everyday domains.",
       "risk", "professional_vs_everyday_orientation_gap",
       source_reference=REF_CAPRICORN_BIO, activation_condition="hard_aspected"),
    _f("capricorn_bio_afflicted_severe_lack_of_imagination", "sign", "Capricorn", "risk",
       _AFFLICTED_PREFIX + "severe lack of imagination.",
       "risk", "severe_lack_of_imagination",
       source_reference=REF_CAPRICORN_BIO, activation_condition="hard_aspected"),
    _f("capricorn_bio_afflicted_difficulty_tuning_into_others_thoughts", "sign", "Capricorn", "risk",
       _AFFLICTED_PREFIX + "difficulty tuning into other people's thoughts.",
       "risk", "difficulty_tuning_into_others_thoughts",
       source_reference=REF_CAPRICORN_BIO, activation_condition="hard_aspected"),
    _f("capricorn_bio_afflicted_difficulty_understanding_others_thinking", "sign", "Capricorn", "risk",
       _AFFLICTED_PREFIX + "difficulty understanding other people's thinking.",
       "risk", "difficulty_understanding_others_thinking",
       source_reference=REF_CAPRICORN_BIO, activation_condition="hard_aspected"),
    _f("capricorn_bio_afflicted_rigid_thinking", "sign", "Capricorn", "risk",
       _AFFLICTED_PREFIX + "rigid thinking.",
       "risk", "rigid_thinking",
       source_reference=REF_CAPRICORN_BIO, activation_condition="hard_aspected"),
    _f("capricorn_bio_afflicted_old_dogma_fixation", "sign", "Capricorn", "risk",
       _AFFLICTED_PREFIX + "old-dogma fixation.",
       "risk", "old_dogma_fixation",
       source_reference=REF_CAPRICORN_BIO, activation_condition="hard_aspected"),
    _f("capricorn_bio_afflicted_duty_rule_bound_thinking", "sign", "Capricorn", "risk",
       _AFFLICTED_PREFIX
       + "duty/rule-bound thinking (\"must / should / proper / obliged\").",
       "risk", "duty_rule_bound_thinking",
       source_reference=REF_CAPRICORN_BIO, activation_condition="hard_aspected"),
)

CAPRICORN_ALL: tuple[SourceFactDef, ...] = (
    CAPRICORN_LESSON7 + CAPRICORN_BIOASTROLOGY + CAPRICORN_AFFLICTED
)

# ---------------------------------------------------------------------------
# Aquarius — Lesson 7
# ---------------------------------------------------------------------------
AQUARIUS_LESSON7: tuple[SourceFactDef, ...] = (
    _f("aquarius_l7_idealistic_thinking", "sign", "Aquarius", "thinking",
       "Idealistic thinking.",
       "strength", "idealistic_thinking",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_global_thinking", "sign", "Aquarius", "thinking",
       "Global thinking.",
       "strength", "global_thinking",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_independent_thinking", "sign", "Aquarius", "thinking",
       "Independent thinking.",
       "strength", "independent_thinking",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_spans_knowledge_areas", "sign", "Aquarius", "thinking",
       "Freely spans knowledge from different areas.",
       "strength", "cross_domain_knowledge_span",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_calculator_in_the_head", "sign", "Aquarius", "thinking",
       "Source describes \"calculator in the head\".",
       "strength", "calculator_in_the_head",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_cycles_many_options_quickly", "sign", "Aquarius", "thinking",
       "Can cycle through many options quickly.",
       "strength", "rapid_option_cycling",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_anomalous_mental_rhythm", "sign", "Aquarius", "thinking",
       "Anomalous / irregular rhythm of mental activity.",
       "neutral", "anomalous_mental_rhythm",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_claircognizance", "sign", "Aquarius", "source_specific",
       "Source wording: claircognizance / insight (source claim; not a scientifically validated ability).",
       "neutral", "source_claircognizance",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_good_memory", "sign", "Aquarius", "memory",
       "Good memory.",
       "strength", "good_memory",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_abstraction_ability", "sign", "Aquarius", "thinking",
       "Abstraction ability.",
       "strength", "abstraction",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_informal_communication", "sign", "Aquarius", "communication",
       "Familiar / informal communication.",
       "neutral", "informal_communication",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_democratic_communication", "sign", "Aquarius", "communication",
       "Democratic communication.",
       "neutral", "democratic_communication",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_speech_varies_with_mood", "sign", "Aquarius", "communication",
       "Speech varies with mood.",
       "neutral", "mood_variable_speech",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_quirky_speech_manner", "sign", "Aquarius", "communication",
       "Quirky / unusual speech manner.",
       "neutral", "quirky_speech",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_extemporaneous_many_topics", "sign", "Aquarius", "communication",
       "Can speak extemporaneously on many topics.",
       "strength", "extemporaneous_many_topics",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_engage_through_genuine_interest", "sign", "Aquarius", "work_application",
       "Development focus: engage through genuine interest.",
       "neutral", "genuine_interest_engagement",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_develop_concreteness_in_decisions", "sign", "Aquarius", "work_application",
       "Development focus: develop concreteness in decisions.",
       "neutral", "decision_concreteness",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_develop_concreteness_in_wording", "sign", "Aquarius", "work_application",
       "Development focus: develop concreteness in wording.",
       "neutral", "wording_concreteness",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_gadgets_can_help", "sign", "Aquarius", "work_application",
       "Gadgets can help.",
       "neutral", "gadgets_support",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_planning_can_help", "sign", "Aquarius", "work_application",
       "Planning can help.",
       "neutral", "planning_support",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_source_genius_intellect_wording", "sign", "Aquarius", "source_specific",
       "Source uses strongest-intellect / genius wording (source claim; not a score, rank, IQ, or hiring conclusion).",
       "neutral", "source_genius_intellect_wording",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_processes_large_data_quickly", "sign", "Aquarius", "learning",
       "Processes large quantities of data quickly.",
       "strength", "rapid_large_data_processing",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_book_learning", "sign", "Aquarius", "learning",
       "Learning through books.",
       "neutral", "book_learning",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_lecture_learning", "sign", "Aquarius", "learning",
       "Learning through lectures.",
       "neutral", "lecture_learning",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_group_learning", "sign", "Aquarius", "learning",
       "Group learning.",
       "neutral", "group_learning",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_discussion_learning", "sign", "Aquarius", "learning",
       "Learning through discussion.",
       "neutral", "discussion_learning",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_independent_learning", "sign", "Aquarius", "learning",
       "Independent learning.",
       "strength", "independent_learning",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_gets_bored_quickly", "sign", "Aquarius", "risk",
       "Gets bored quickly.",
       "risk", "quick_boredom",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_lack_of_patience", "sign", "Aquarius", "risk",
       "Lack of patience.",
       "risk", "lack_of_patience",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_lack_of_systematicity", "sign", "Aquarius", "risk",
       "Lack of systematicity.",
       "risk", "lack_of_systematicity",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_scattering_dispersion", "sign", "Aquarius", "risk",
       "Difficulty: scattering / dispersion of attention or interests.",
       "risk", "attention_interest_dispersion",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_env_broad_social_circle", "sign", "Aquarius", "environment",
       "Broad social circle.",
       "neutral", "broad_social_circle",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_env_friendly_siblings", "sign", "Aquarius", "environment",
       "Friendly sibling relationships.",
       "neutral", "friendly_sibling_relationships",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_env_unpredictable_siblings", "sign", "Aquarius", "environment",
       "Unpredictable sibling relationships.",
       "neutral", "unpredictable_sibling_relationships",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_env_unusual_environment", "sign", "Aquarius", "environment",
       "Unusual environment.",
       "neutral", "unusual_environment",
       source_reference=REF_AQUARIUS_L7),
    _f("aquarius_l7_env_futuristic_environment", "sign", "Aquarius", "environment",
       "Futuristic environment.",
       "neutral", "futuristic_environment",
       source_reference=REF_AQUARIUS_L7),
)

AQUARIUS_BIOASTROLOGY: tuple[SourceFactDef, ...] = (
    _f("aquarius_bio_uranian_freedom_equality_fraternity_coloring", "sign", "Aquarius", "source_specific",
       "Mercury functions colored by Uranian freedom/equality/fraternity (source framing; not a scientific statement).",
       "neutral", "uranian_freedom_equality_fraternity_coloring",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_creativity", "sign", "Aquarius", "thinking",
       "Creativity.",
       "strength", "creativity",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_source_genius_intellect_archetype", "sign", "Aquarius", "source_specific",
       "Source archetypically describes this as one of the most \"genius\" intellects (source claim; not a score, rank, IQ, or hiring conclusion).",
       "neutral", "source_genius_intellect_wording",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_technical_scientific_aptitude", "sign", "Aquarius", "work_application",
       "Technical/scientific aptitude (source-described tendency).",
       "strength", "technical_scientific_aptitude",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_inventor_aptitude", "sign", "Aquarius", "work_application",
       "Inventor aptitude (source-described tendency).",
       "strength", "inventor_aptitude",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_knowledge_fragment_synthesis", "sign", "Aquarius", "thinking",
       "Synthesis of different knowledge fragments into one narrative.",
       "strength", "knowledge_fragment_synthesis",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_artistic_aptitude", "sign", "Aquarius", "work_application",
       "Artistic aptitude association (source-described).",
       "strength", "artistic_aptitude",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_creative_thinking", "sign", "Aquarius", "thinking",
       "Creative thinking.",
       "strength", "creative_thinking",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_insights", "sign", "Aquarius", "thinking",
       "Insights.",
       "strength", "insight",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_strong_firm_memory", "sign", "Aquarius", "memory",
       "Strong / firm memory.",
       "strength", "strong_memory",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_planning", "sign", "Aquarius", "thinking",
       "Planning.",
       "strength", "planning",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_forecasting", "sign", "Aquarius", "thinking",
       "Forecasting.",
       "strength", "forecasting",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_interest_in_future", "sign", "Aquarius", "learning",
       "Interest in future.",
       "neutral", "interest_in_future",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_interest_science_fiction", "sign", "Aquarius", "learning",
       "Interest in science fiction.",
       "neutral", "interest_science_fiction",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_interest_technology", "sign", "Aquarius", "learning",
       "Interest in technology.",
       "neutral", "interest_technology",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_curiosity", "sign", "Aquarius", "learning",
       "Curiosity.",
       "neutral", "curiosity",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_continual_learning_courses", "sign", "Aquarius", "learning",
       "Continual learning / likes courses.",
       "strength", "continual_course_learning",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_erudition", "sign", "Aquarius", "thinking",
       "Erudition.",
       "strength", "erudition",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_extemporaneous_many_topics", "sign", "Aquarius", "communication",
       "Ability to speak extemporaneously on many topics.",
       "strength", "extemporaneous_many_topics",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_learning_group_communication", "sign", "Aquarius", "learning",
       "Learning through group communication.",
       "neutral", "group_communication_learning",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_learning_lectures", "sign", "Aquarius", "learning",
       "Learning through lectures.",
       "neutral", "lecture_learning",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_learning_audio", "sign", "Aquarius", "learning",
       "Learning through audio.",
       "neutral", "audio_learning",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_learning_video", "sign", "Aquarius", "learning",
       "Learning through video.",
       "neutral", "video_learning",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_learning_books", "sign", "Aquarius", "learning",
       "Learning through books.",
       "neutral", "book_learning",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_motivation_natural_curiosity", "sign", "Aquarius", "learning",
       "Learning motivation: natural curiosity.",
       "neutral", "curiosity_motivated_learning",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_motivation_fresh_information", "sign", "Aquarius", "learning",
       "Learning motivation: constant need for fresh information.",
       "neutral", "fresh_information_need",
       source_reference=REF_AQUARIUS_BIO),
    _f("aquarius_bio_motivation_extraordinary_new_information", "sign", "Aquarius", "learning",
       "Learning motivation: attraction to extraordinary / unusual new information.",
       "neutral", "extraordinary_new_information_attraction",
       source_reference=REF_AQUARIUS_BIO),
)

AQUARIUS_AFFLICTED: tuple[SourceFactDef, ...] = (
    _f("aquarius_bio_afflicted_instability_of_thinking", "sign", "Aquarius", "risk",
       _AFFLICTED_PREFIX + "instability of thinking.",
       "risk", "thinking_instability",
       source_reference=REF_AQUARIUS_BIO, activation_condition="hard_aspected"),
    _f("aquarius_bio_afflicted_instability_of_learning", "sign", "Aquarius", "risk",
       _AFFLICTED_PREFIX + "instability of learning.",
       "risk", "learning_instability",
       source_reference=REF_AQUARIUS_BIO, activation_condition="hard_aspected"),
    _f("aquarius_bio_afflicted_anomalous_rhythms", "sign", "Aquarius", "risk",
       _AFFLICTED_PREFIX + "anomalous rhythms.",
       "risk", "anomalous_rhythms",
       source_reference=REF_AQUARIUS_BIO, activation_condition="hard_aspected"),
    _f("aquarius_bio_afflicted_idea_waves_then_irritation_slowdown", "sign", "Aquarius", "risk",
       _AFFLICTED_PREFIX
       + "waves of many ideas followed by irritation / mental slowdown.",
       "risk", "idea_waves_then_irritation_slowdown",
       source_reference=REF_AQUARIUS_BIO, activation_condition="hard_aspected"),
    _f("aquarius_bio_afflicted_irregular_broken_speech_tempo", "sign", "Aquarius", "risk",
       _AFFLICTED_PREFIX + "irregular / broken speech tempo.",
       "risk", "irregular_broken_speech_tempo",
       source_reference=REF_AQUARIUS_BIO, activation_condition="hard_aspected"),
    _f("aquarius_bio_afflicted_source_adhd_effect_wording", "sign", "Aquarius", "source_specific",
       _AFFLICTED_PREFIX
       + "source uses \"ADHD effect\" wording (source-described, non-diagnostic; not a medical conclusion).",
       "risk", "source_adhd_effect_wording",
       source_reference=REF_AQUARIUS_BIO, activation_condition="hard_aspected"),
    _f("aquarius_bio_afflicted_loss_of_focus", "sign", "Aquarius", "risk",
       _AFFLICTED_PREFIX + "loss of focus.",
       "risk", "loss_of_focus",
       source_reference=REF_AQUARIUS_BIO, activation_condition="hard_aspected"),
    _f("aquarius_bio_afflicted_broad_fragmentary_general_knowledge", "sign", "Aquarius", "risk",
       _AFFLICTED_PREFIX + "broad fragmentary general knowledge.",
       "risk", "broad_fragmentary_general_knowledge",
       source_reference=REF_AQUARIUS_BIO, activation_condition="hard_aspected"),
    _f("aquarius_bio_afflicted_insufficient_depth_despite_breadth", "sign", "Aquarius", "risk",
       _AFFLICTED_PREFIX + "insufficient depth despite breadth.",
       "risk", "insufficient_depth_despite_breadth",
       source_reference=REF_AQUARIUS_BIO, activation_condition="hard_aspected"),
)

AQUARIUS_ALL: tuple[SourceFactDef, ...] = (
    AQUARIUS_LESSON7 + AQUARIUS_BIOASTROLOGY + AQUARIUS_AFFLICTED
)

# ---------------------------------------------------------------------------
# Pisces — Lesson 7
# ---------------------------------------------------------------------------
PISCES_LESSON7: tuple[SourceFactDef, ...] = (
    _f("pisces_l7_overall_impression_over_isolated_fact", "sign", "Pisces", "thinking",
       "Catches overall impression rather than isolated fact.",
       "strength", "overall_impression_perception",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_image_based_perception", "sign", "Pisces", "thinking",
       "Image-based perception.",
       "strength", "image_based_perception",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_exceptionally_strong_imagination", "sign", "Pisces", "thinking",
       "Source says exceptionally strong imagination.",
       "strength", "strong_imagination",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_nonobvious_logic", "sign", "Pisces", "thinking",
       "Logic described as difficult to comprehend / non-obvious.",
       "neutral", "nonobvious_logic",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_high_intuition", "sign", "Pisces", "source_specific",
       "High intuition (source claim; not a scientifically established ability).",
       "strength", "intuition",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_mystical_thinking", "sign", "Pisces", "source_specific",
       "Mystical thinking / searches for hidden meaning (source claim).",
       "neutral", "mystical_thinking",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_suggestibility", "sign", "Pisces", "risk",
       "Suggestibility.",
       "risk", "suggestibility",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_manipulation_susceptibility", "sign", "Pisces", "risk",
       "Susceptibility to manipulation.",
       "risk", "manipulation_susceptibility",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_correct_decisions_nonrational_routes", "sign", "Pisces", "source_specific",
       "Source says correct decisions may sometimes emerge by unclear/non-rational routes (source claim).",
       "neutral", "nonrational_correct_decision_routes",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_harmonious_communication", "sign", "Pisces", "communication",
       "Harmonious communication.",
       "strength", "harmonious_communication",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_calm_communication", "sign", "Pisces", "communication",
       "Calm communication.",
       "neutral", "calm_communication",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_soulful_communication", "sign", "Pisces", "communication",
       "Soulful / emotionally attuned communication.",
       "strength", "soulful_communication",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_unclear_speech", "sign", "Pisces", "communication",
       "Speech can be unclear.",
       "risk", "unclear_speech",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_emotional_speech", "sign", "Pisces", "communication",
       "Emotional speech.",
       "neutral", "emotional_speech",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_compressed_crumpled_speech", "sign", "Pisces", "communication",
       "Compressed / crumpled speech.",
       "risk", "crumpled_speech",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_speech_may_lack_central_idea", "sign", "Pisces", "communication",
       "Speech may lack a central idea.",
       "risk", "lack_of_central_idea",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_speaks_through_parables", "sign", "Pisces", "communication",
       "Speaks through parables.",
       "neutral", "parable_speech",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_speaks_through_riddles", "sign", "Pisces", "communication",
       "Speaks through riddles.",
       "neutral", "riddle_speech",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_sensitivity_to_hidden_intonation", "sign", "Pisces", "communication",
       "Sensitivity to hidden / underlying intonation.",
       "strength", "hidden_intonation_sensitivity",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_dev_formulate_central_idea", "sign", "Pisces", "work_application",
       "Development focus: formulate the central idea.",
       "neutral", "formulate_central_idea",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_dev_distinguish_own_vs_suggested", "sign", "Pisces", "work_application",
       "Development focus: distinguish one's own thoughts from suggested / imposed illusions.",
       "neutral", "distinguish_own_vs_suggested_thoughts",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_dev_alternate_speech_with_silence", "sign", "Pisces", "work_application",
       "Development focus: alternate speech flow with conscious silence.",
       "neutral", "alternate_speech_with_silence",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_learning_images", "sign", "Pisces", "learning",
       "Learning through images.",
       "neutral", "image_learning",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_learning_video", "sign", "Pisces", "learning",
       "Learning through video.",
       "neutral", "video_learning",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_learning_photos", "sign", "Pisces", "learning",
       "Learning through photos.",
       "neutral", "photo_learning",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_learning_intuitive_impression", "sign", "Pisces", "learning",
       "Learning through intuitive impression.",
       "neutral", "intuitive_impression_learning",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_learning_listening", "sign", "Pisces", "learning",
       "Learning through listening.",
       "neutral", "listening_learning",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_learning_absorbing_overall_impression", "sign", "Pisces", "learning",
       "Learning by absorbing / forming an overall impression.",
       "neutral", "overall_impression_learning",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_learning_solitude", "sign", "Pisces", "learning",
       "Learning in solitude.",
       "neutral", "solitude_learning",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_unconventional_learning", "sign", "Pisces", "learning",
       "Unconventional learning.",
       "neutral", "unconventional_learning",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_creative_reinterpretation_learning", "sign", "Pisces", "learning",
       "Creative reinterpretation in learning.",
       "neutral", "creative_reinterpretation_learning",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_captivity_in_illusions", "sign", "Pisces", "risk",
       "Difficulty: captivity in illusions.",
       "risk", "captivity_in_illusions",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_words_can_diverge_from_reality", "sign", "Pisces", "risk",
       "Difficulty: words can diverge from reality.",
       "risk", "words_diverge_from_reality",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_env_adapts_to_collective_stereotypes", "sign", "Pisces", "environment",
       "Adapts to collective stereotypes.",
       "neutral", "collective_stereotype_adaptation",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_env_soulful_siblings", "sign", "Pisces", "environment",
       "Soulful sibling relationships.",
       "neutral", "soulful_sibling_relationships",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_env_sibling_illusions", "sign", "Pisces", "environment",
       "Possible illusions in sibling relationships.",
       "risk", "sibling_relationship_illusions",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_env_possible_misunderstanding", "sign", "Pisces", "environment",
       "Possible misunderstanding in the close environment.",
       "risk", "environmental_misunderstanding",
       source_reference=REF_PISCES_L7),
    _f("pisces_l7_env_avoids_polemics", "sign", "Pisces", "environment",
       "Avoids polemics in close environment.",
       "neutral", "avoids_polemics_in_close_environment",
       source_reference=REF_PISCES_L7),
)

PISCES_BIOASTROLOGY: tuple[SourceFactDef, ...] = (
    _f("pisces_bio_minor_exile", "sign", "Pisces", "source_specific",
       "Source calls the placement \"minor exile\" (source status statement; not a skill score).",
       "neutral", "minor_exile",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_lose_grip_on_factual_reality", "sign", "Pisces", "risk",
       "Thinking/learning can lose grip on factual texture of reality.",
       "risk", "lose_grip_on_factual_reality",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_unusually_strong_intuition", "sign", "Pisces", "source_specific",
       "Source claims unusually strong intuition (source claim; not a scientifically established ability).",
       "strength", "intuition",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_humanities_aptitude", "sign", "Pisces", "work_application",
       "Humanitarian/humanities aptitude (source-described tendency).",
       "strength", "humanities_aptitude",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_lyrical_talent", "sign", "Pisces", "work_application",
       "Lyrical talent (source-described tendency).",
       "strength", "lyrical_talent",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_poetic_talent", "sign", "Pisces", "work_application",
       "Poetic talent (source-described tendency).",
       "strength", "poetic_talent",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_languages_aptitude", "sign", "Pisces", "work_application",
       "Languages aptitude (source-described tendency).",
       "strength", "languages_aptitude",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_universal_cosmic_intellect_synthesis", "sign", "Pisces", "source_specific",
       "Source describes a universal/cosmic intellect synthesizing knowledge from different fields (source claim).",
       "neutral", "universal_cosmic_intellect_synthesis",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_loses_disputes_insufficient_assertiveness", "sign", "Pisces", "communication",
       "Often loses disputes because of insufficient pressure/assertiveness.",
       "risk", "loses_disputes_insufficient_assertiveness",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_public_speaking_requires_training", "sign", "Pisces", "communication",
       "Public speaking requires training.",
       "neutral", "public_speaking_requires_training",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_public_speaking_requires_preparation", "sign", "Pisces", "communication",
       "Public speaking requires preparation.",
       "neutral", "public_speaking_requires_preparation",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_selective_memory", "sign", "Pisces", "memory",
       "Memory is selective.",
       "neutral", "selective_memory",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_context_dependent_memory", "sign", "Pisces", "memory",
       "Memory is highly context-dependent.",
       "neutral", "context_dependent_memory",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_memory_range_chart_context", "sign", "Pisces", "memory",
       "Source says memory may range from exceptional to very poor depending on chart context "
       "(conditional/context-dependent; not an absolute strong_memory or poor_memory claim).",
       "neutral", "context_variable_memory_range",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_learning_flow_state", "sign", "Pisces", "learning",
       "Learning through flow state.",
       "neutral", "flow_state_learning",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_learning_emotional_psychological_attunement", "sign", "Pisces", "learning",
       "Learning through emotional / psychological attunement with real people.",
       "neutral", "emotional_psychological_attunement_learning",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_learning_books", "sign", "Pisces", "learning",
       "Learning through books.",
       "neutral", "book_learning",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_learning_youtube_content_video", "sign", "Pisces", "learning",
       "Learning through YouTube/content video.",
       "neutral", "video_content_learning",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_learning_audio", "sign", "Pisces", "learning",
       "Learning through audio.",
       "neutral", "audio_learning",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_motivation_mystery", "sign", "Pisces", "learning",
       "Learning motivation: mystery.",
       "neutral", "mystery_motivation",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_motivation_mystico_psychological_engagement", "sign", "Pisces", "learning",
       "Learning motivation: mystico-psychological emotional engagement.",
       "neutral", "mystico_psychological_engagement_motivation",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_motivation_emotional_atmosphere", "sign", "Pisces", "learning",
       "Learning motivation: emotional atmosphere.",
       "neutral", "emotional_atmosphere_motivation",
       source_reference=REF_PISCES_BIO),
    _f("pisces_bio_motivation_kindred_people", "sign", "Pisces", "learning",
       "Learning motivation: sense of being among intellectually/emotionally kindred people.",
       "neutral", "kindred_people_motivation",
       source_reference=REF_PISCES_BIO),
)

PISCES_AFFLICTED: tuple[SourceFactDef, ...] = (
    _f("pisces_bio_afflicted_lying_distortion", "sign", "Pisces", "risk",
       _AFFLICTED_PREFIX + "lying / distortion tendency.",
       "risk", "lying_distortion",
       source_reference=REF_PISCES_BIO, activation_condition="hard_aspected"),
    _f("pisces_bio_afflicted_mystification", "sign", "Pisces", "risk",
       _AFFLICTED_PREFIX + "mystification.",
       "risk", "mystification",
       source_reference=REF_PISCES_BIO, activation_condition="hard_aspected"),
    _f("pisces_bio_afflicted_suggestibility", "sign", "Pisces", "risk",
       _AFFLICTED_PREFIX + "suggestibility.",
       "risk", "suggestibility",
       source_reference=REF_PISCES_BIO, activation_condition="hard_aspected"),
    _f("pisces_bio_afflicted_words_exceed_completed_actions", "sign", "Pisces", "risk",
       _AFFLICTED_PREFIX + "words can greatly exceed completed actions/results.",
       "risk", "words_exceed_completed_actions",
       source_reference=REF_PISCES_BIO, activation_condition="hard_aspected"),
    _f("pisces_bio_afflicted_unclear_speech", "sign", "Pisces", "risk",
       _AFFLICTED_PREFIX + "unclear speech.",
       "risk", "unclear_speech",
       source_reference=REF_PISCES_BIO, activation_condition="hard_aspected"),
    _f("pisces_bio_afflicted_crumpled_speech", "sign", "Pisces", "risk",
       _AFFLICTED_PREFIX + "crumpled speech.",
       "risk", "crumpled_speech",
       source_reference=REF_PISCES_BIO, activation_condition="hard_aspected"),
    _f("pisces_bio_afflicted_lack_of_central_idea", "sign", "Pisces", "risk",
       _AFFLICTED_PREFIX + "lack of central idea.",
       "risk", "lack_of_central_idea",
       source_reference=REF_PISCES_BIO, activation_condition="hard_aspected"),
    _f("pisces_bio_afflicted_lack_of_structure", "sign", "Pisces", "risk",
       _AFFLICTED_PREFIX + "lack of structure.",
       "risk", "lack_of_structure",
       source_reference=REF_PISCES_BIO, activation_condition="hard_aspected"),
    _f("pisces_bio_afflicted_lack_of_logic", "sign", "Pisces", "risk",
       _AFFLICTED_PREFIX + "lack of logic.",
       "risk", "lack_of_logic",
       source_reference=REF_PISCES_BIO, activation_condition="hard_aspected"),
    _f("pisces_bio_afflicted_information_chaos", "sign", "Pisces", "risk",
       _AFFLICTED_PREFIX + "contradictory informational mixture / information chaos.",
       "risk", "information_chaos",
       source_reference=REF_PISCES_BIO, activation_condition="hard_aspected"),
)

PISCES_ALL: tuple[SourceFactDef, ...] = PISCES_LESSON7 + PISCES_BIOASTROLOGY + PISCES_AFFLICTED

A3_SIGN_PACKS: tuple[SourceFactDef, ...] = CAPRICORN_ALL + AQUARIUS_ALL + PISCES_ALL
