"""Mercury Source Profile v2 — Sign Batch A2 dual-source packs.

Signs: Virgo, Libra, Scorpio
Sources: Lesson 7 Mercury + Bioastrology \"Знаки Меркурия\"

SOURCE FIRST → SYNTHESIS SECOND.
Dual sources on the same sign do NOT create repeated signals by themselves.

Local SourceFactDef/_f avoid circular import with mercury_source_knowledge.py.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SourceFactDef:
    id: str
    factor_type: str
    factor_key: str
    category: str
    text: str
    polarity: str
    tags: tuple[str, ...] = ()
    source_reference: str = ""
    activation_condition: str | None = None
    unresolved: bool = False


def _f(
    id: str,
    factor_type: str,
    factor_key: str,
    category: str,
    text: str,
    polarity: str,
    *tags: str,
    source_reference: str,
    activation_condition: str | None = None,
    unresolved: bool = False,
) -> SourceFactDef:
    return SourceFactDef(
        id=id,
        factor_type=factor_type,
        factor_key=factor_key,
        category=category,
        text=text,
        polarity=polarity,
        tags=tags,
        source_reference=source_reference,
        activation_condition=activation_condition,
        unresolved=unresolved,
    )


REF_VIRGO_L7 = "lesson7_mercury_virgo"
REF_VIRGO_BIO = "bioastrology_mercury_virgo"
REF_LIBRA_L7 = "lesson7_mercury_libra"
REF_LIBRA_BIO = "bioastrology_mercury_libra"
REF_SCORPIO_L7 = "lesson7_mercury_scorpio"
REF_SCORPIO_BIO = "bioastrology_mercury_scorpio"

_AFFLICTED_PREFIX = (
    "Source affliction tendency (activated via project hard_aspected proxy "
    "for 'при поражении'): "
)

# ---------------------------------------------------------------------------
# Virgo — Lesson 7
# ---------------------------------------------------------------------------
VIRGO_LESSON7: tuple[SourceFactDef, ...] = (
    _f("virgo_l7_selective_thinking", "sign", "Virgo", "thinking",
       "Selective thinking.",
       "strength", "selective_thinking",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_analytical_thinking", "sign", "Virgo", "thinking",
       "Analytical thinking.",
       "strength", "analytical_thinking",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_selects_significant_arguments", "sign", "Virgo", "thinking",
       "Identifies / selects significant arguments.",
       "strength", "argument_selection",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_strongest_logic_after_preparation", "sign", "Virgo", "thinking",
       "Strongest logic after preparation and thinking through.",
       "strength", "prepared_logic",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_emotionally_cool", "sign", "Virgo", "thinking",
       "Emotionally cool / not easily moved by emotion.",
       "neutral", "emotionally_cool",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_strong_tactical_thinking", "sign", "Virgo", "thinking",
       "Strong tactical thinking.",
       "strength", "tactical_thinking",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_weaker_strategic_overview", "sign", "Virgo", "thinking",
       "Weaker strategic overview.",
       "risk", "weak_strategic_overview",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_dispersion_into_small_details", "sign", "Virgo", "thinking",
       "Dispersion into small details.",
       "risk", "detail_dispersion",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_fixation_on_everyday_details", "sign", "Virgo", "thinking",
       "Fixation on everyday/routine details.",
       "risk", "routine_detail_fixation",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_precision_of_formulations", "sign", "Virgo", "communication",
       "Precision of formulations.",
       "strength", "precise_formulations",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_tendency_to_clarify_details", "sign", "Virgo", "communication",
       "Tendency to clarify details.",
       "neutral", "detail_clarification",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_simple_direct_communication", "sign", "Virgo", "communication",
       "Simple/direct communication style.",
       "neutral", "simple_direct_communication",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_limited_contact_circle", "sign", "Virgo", "communication",
       "Limited contact circle.",
       "neutral", "limited_contact_circle",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_proper_intonation", "sign", "Virgo", "communication",
       "Proper/correct intonation.",
       "neutral", "proper_intonation",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_observation_keeping", "sign", "Virgo", "communication",
       "Observation keeping.",
       "strength", "observation_keeping",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_diary_recording_tendency", "sign", "Virgo", "communication",
       "Diary / recording tendency.",
       "neutral", "diary_recording",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_statistics_tracking", "sign", "Virgo", "communication",
       "Statistics tracking.",
       "neutral", "statistics_tracking",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_dev_build_schemes", "sign", "Virgo", "work_application",
       "Development focus: build schemes.",
       "neutral", "scheme_building",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_dev_construct_methodology", "sign", "Virgo", "work_application",
       "Development focus: construct methodology.",
       "neutral", "methodology_construction",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_dev_put_each_detail_in_place", "sign", "Virgo", "work_application",
       "Development focus: put each detail into its place.",
       "neutral", "detail_placement",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_dev_remove_unnecessary", "sign", "Virgo", "work_application",
       "Development focus: remove unnecessary elements.",
       "neutral", "remove_unnecessary",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_dev_avoid_micromanagement", "sign", "Virgo", "work_application",
       "Development focus: avoid micromanagement.",
       "neutral", "avoid_micromanagement",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_practical_learning", "sign", "Virgo", "learning",
       "Practical learning.",
       "strength", "practice_based_learning",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_learning_notes", "sign", "Virgo", "learning",
       "Learning support: notes.",
       "neutral", "notes_learning",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_learning_algorithms", "sign", "Virgo", "learning",
       "Learning support: algorithms.",
       "neutral", "algorithm_learning",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_learning_schemes", "sign", "Virgo", "learning",
       "Learning support: schemes.",
       "neutral", "scheme_learning",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_learning_tables", "sign", "Virgo", "learning",
       "Learning support: tables.",
       "neutral", "table_learning",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_learning_compile_others_opinions", "sign", "Virgo", "learning",
       "Learning support: compilation of other people's opinions.",
       "neutral", "opinion_compilation_learning",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_risk_routine_fixation", "sign", "Virgo", "risk",
       "Difficulty: routine fixation.",
       "risk", "routine_fixation",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_risk_losing_whole_picture", "sign", "Virgo", "risk",
       "Difficulty: losing the whole picture because of details.",
       "risk", "big_picture_risk",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_env_limited_social_circle", "sign", "Virgo", "environment",
       "Limited social/contact circle.",
       "neutral", "limited_social_circle",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_env_connections_from_duty", "sign", "Virgo", "environment",
       "Maintaining connections from duty/propriety.",
       "neutral", "duty_based_connections",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_env_practical_sibling_communication", "sign", "Virgo", "environment",
       "Practical/useful communication with siblings.",
       "neutral", "practical_sibling_communication",
       source_reference=REF_VIRGO_L7),
    _f("virgo_l7_env_low_emotionality_siblings", "sign", "Virgo", "environment",
       "Low emotionality in sibling communication.",
       "neutral", "low_emotionality_sibling_communication",
       source_reference=REF_VIRGO_L7),
)

VIRGO_BIOASTROLOGY: tuple[SourceFactDef, ...] = (
    _f("virgo_bio_minor_domicile_near_sync", "sign", "Virgo", "source_specific",
       "Minor domicile / near synchronization of Mercury and Virgo sign environment (source status statement; not a skill score).",
       "neutral", "minor_domicile_near_sync",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_strong_erudition", "sign", "Virgo", "thinking",
       "Strong erudition.",
       "strength", "erudition",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_skill_operating_facts", "sign", "Virgo", "thinking",
       "Skill operating facts.",
       "strength", "fact_operation",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_sticky_strong_memory", "sign", "Virgo", "memory",
       "Sticky/strong memory.",
       "strength", "sticky_strong_memory",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_strong_attention", "sign", "Virgo", "focus",
       "Strong attention.",
       "strength", "strong_attention",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_learning_on_the_fly", "sign", "Virgo", "learning",
       "Learning on the fly.",
       "strength", "learning_on_the_fly",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_grounded_thinking", "sign", "Virgo", "thinking",
       "Grounded thinking.",
       "strength", "grounded_thinking",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_somewhat_dry_thinking_learning", "sign", "Virgo", "thinking",
       "Somewhat dry thinking/learning.",
       "neutral", "dry_thinking_learning",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_speech_lacks_expressive_zest", "sign", "Virgo", "communication",
       "Speech may lack expressive \"zest\".",
       "risk", "speech_lacks_expressive_zest",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_technical_aptitude", "sign", "Virgo", "work_application",
       "Technical aptitude (source-described tendency).",
       "strength", "technical_ability",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_legal_aptitude", "sign", "Virgo", "work_application",
       "Legal aptitude (source-described tendency).",
       "strength", "legal_ability",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_writing_aptitude", "sign", "Virgo", "work_application",
       "Writing aptitude (source-described tendency).",
       "strength", "writing",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_literary_aptitude", "sign", "Virgo", "work_application",
       "Literary aptitude (source-described tendency).",
       "strength", "literary_aptitude",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_deliberately_correct_speech", "sign", "Virgo", "communication",
       "Deliberately correct speech.",
       "strength", "correct_speech",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_strongly_articulated_wording", "sign", "Virgo", "communication",
       "Strongly articulated / \"stamped\" wording.",
       "strength", "articulated_wording",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_high_mastery_of_words", "sign", "Virgo", "communication",
       "Potential for very high mastery of words.",
       "strength", "word_mastery",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_occupation_associations", "sign", "Virgo", "source_specific",
       "Source-described occupation associations include writers, scientists, officials, and backstage negotiators; not career assignments.",
       "neutral", "occupation_associations",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_independent_analysis_learning", "sign", "Virgo", "learning",
       "Learning through independent analysis of material.",
       "strength", "independent_analysis_learning",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_motivation_curiosity", "sign", "Virgo", "learning",
       "Learning motivation: curiosity.",
       "neutral", "curiosity_motivated_learning",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_motivation_practical_usefulness", "sign", "Virgo", "learning",
       "Learning motivation: practical usefulness is required/important.",
       "neutral", "practical_usefulness_motivation",
       source_reference=REF_VIRGO_BIO),
    _f("virgo_bio_less_accumulation_for_its_own_sake", "sign", "Virgo", "learning",
       "Learning merely for accumulation of knowledge is less characteristic than in the source comparison with Gemini.",
       "neutral", "less_knowledge_accumulation_for_its_own_sake",
       source_reference=REF_VIRGO_BIO),
)

VIRGO_AFFLICTED: tuple[SourceFactDef, ...] = (
    _f("virgo_bio_afflicted_tediousness", "sign", "Virgo", "risk",
       _AFFLICTED_PREFIX + "tediousness.",
       "risk", "tediousness",
       source_reference=REF_VIRGO_BIO, activation_condition="hard_aspected"),
    _f("virgo_bio_afflicted_pettiness", "sign", "Virgo", "risk",
       _AFFLICTED_PREFIX + "pettiness.",
       "risk", "pettiness",
       source_reference=REF_VIRGO_BIO, activation_condition="hard_aspected"),
    _f("virgo_bio_afflicted_cannot_see_forest_for_trees", "sign", "Virgo", "risk",
       _AFFLICTED_PREFIX + "inability to see forest for trees.",
       "risk", "forest_for_trees_loss",
       source_reference=REF_VIRGO_BIO, activation_condition="hard_aspected"),
    _f("virgo_bio_afflicted_collecting_facts_without_central_idea", "sign", "Virgo", "risk",
       _AFFLICTED_PREFIX + "collecting facts without central idea.",
       "risk", "facts_without_central_idea",
       source_reference=REF_VIRGO_BIO, activation_condition="hard_aspected"),
    _f("virgo_bio_afflicted_collecting_facts_without_conclusion", "sign", "Virgo", "risk",
       _AFFLICTED_PREFIX + "collecting facts without conclusion.",
       "risk", "facts_without_conclusion",
       source_reference=REF_VIRGO_BIO, activation_condition="hard_aspected"),
)

VIRGO_ALL: tuple[SourceFactDef, ...] = VIRGO_LESSON7 + VIRGO_BIOASTROLOGY + VIRGO_AFFLICTED

# ---------------------------------------------------------------------------
# Libra — Lesson 7
# ---------------------------------------------------------------------------
LIBRA_LESSON7: tuple[SourceFactDef, ...] = (
    _f("libra_l7_high_speed_of_comprehension", "sign", "Libra", "thinking",
       "High speed of comprehension.",
       "strength", "comprehension_speed",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_high_receptivity", "sign", "Libra", "learning",
       "High receptivity.",
       "strength", "receptivity",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_assimilation_through_discussion", "sign", "Libra", "learning",
       "Assimilation through discussion.",
       "strength", "discussion_learning",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_view_issue_from_multiple_sides", "sign", "Libra", "thinking",
       "Ability to view an issue from multiple sides.",
       "strength", "perspective_comparison",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_learning_through_contradiction_comparison", "sign", "Libra", "learning",
       "Learning through comparison of contradictions.",
       "strength", "contradiction_comparison_learning",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_evaluates_via_aesthetic_beauty", "sign", "Libra", "thinking",
       "Evaluates intellectual constructions through aesthetic beauty.",
       "neutral", "aesthetic_evaluation",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_evaluates_via_completeness", "sign", "Libra", "thinking",
       "Evaluates intellectual constructions through completeness.",
       "neutral", "completeness_evaluation",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_delicate_communication", "sign", "Libra", "communication",
       "Delicate communication.",
       "strength", "delicate_communication",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_peaceful_communication", "sign", "Libra", "communication",
       "Peaceful communication.",
       "strength", "peaceful_communication",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_conversational_adaptation", "sign", "Libra", "communication",
       "Conversational adaptation / chameleon-like adjustment.",
       "neutral", "conversational_adaptation",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_skill_with_compliments", "sign", "Libra", "communication",
       "Skill with compliments.",
       "strength", "compliments",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_says_what_interlocutor_wants", "sign", "Libra", "communication",
       "Tendency to say what interlocutor wants to hear.",
       "risk", "audience_pleasing_speech",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_information_synthesis", "sign", "Libra", "thinking",
       "Information synthesis.",
       "strength", "information_synthesis",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_appeal_to_fairness", "sign", "Libra", "communication",
       "Appeal to fairness.",
       "neutral", "fairness_appeal",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_difficulty_making_decisions", "sign", "Libra", "risk",
       "Difficulty making decisions after prolonged weighing.",
       "risk", "decision_difficulty_after_weighing",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_endless_pros_cons_weighing", "sign", "Libra", "risk",
       "Endless pros/cons weighing.",
       "risk", "endless_pros_cons_weighing",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_reluctance_to_take_one_side", "sign", "Libra", "risk",
       "Reluctance/fear to take one side.",
       "risk", "reluctance_to_take_side",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_support_dialogue", "sign", "Libra", "learning",
       "Learning support: dialogue.",
       "neutral", "dialogue_learning",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_support_live_teacher", "sign", "Libra", "learning",
       "Learning support: live teacher.",
       "neutral", "live_teacher_learning",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_support_live_peer", "sign", "Libra", "learning",
       "Learning support: live peer.",
       "neutral", "live_peer_learning",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_support_exchange_of_opinions", "sign", "Libra", "learning",
       "Learning support: exchange of opinions.",
       "neutral", "opinion_exchange_learning",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_support_books", "sign", "Libra", "learning",
       "Learning support: books.",
       "neutral", "book_learning",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_support_lectures", "sign", "Libra", "learning",
       "Learning support: lectures.",
       "neutral", "lecture_learning",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_support_aesthetic_environment", "sign", "Libra", "learning",
       "Learning support: aesthetic learning environment.",
       "neutral", "aesthetic_learning_environment",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_support_peer_collaboration", "sign", "Libra", "learning",
       "Learning support: peer collaboration on difficult problems.",
       "neutral", "peer_collaboration_learning",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_risk_serving_two_masters", "sign", "Libra", "risk",
       "Difficulty: serving \"two masters\".",
       "risk", "serving_two_masters",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_risk_avoiding_dispute", "sign", "Libra", "risk",
       "Difficulty: avoiding dispute.",
       "risk", "dispute_avoidance",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_env_tendency_to_form_relationships", "sign", "Libra", "environment",
       "Tendency to form relationships.",
       "neutral", "relationship_forming",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_env_search_for_common_language", "sign", "Libra", "environment",
       "Search for common language.",
       "neutral", "common_language_search",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_env_easy_quick_contact", "sign", "Libra", "environment",
       "Easy/quick contact.",
       "strength", "easy_quick_contact",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_env_sibling_diplomacy", "sign", "Libra", "environment",
       "Sibling diplomacy.",
       "neutral", "sibling_diplomacy",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_env_sibling_dispute_avoidance", "sign", "Libra", "environment",
       "Sibling dispute avoidance.",
       "risk", "sibling_dispute_avoidance",
       source_reference=REF_LIBRA_L7),
    _f("libra_l7_env_consultant_smoothing_role", "sign", "Libra", "environment",
       "Consultant / smoothing-corners role.",
       "neutral", "smoothing_corners_role",
       source_reference=REF_LIBRA_L7),
)

LIBRA_BIOASTROLOGY: tuple[SourceFactDef, ...] = (
    _f("libra_bio_venusian_diplomacy_aesthetic_coloring", "sign", "Libra", "thinking",
       "Mercury thinking/communication/learning colored by Venusian diplomacy/aesthetic quality.",
       "neutral", "venusian_diplomacy_aesthetic_coloring",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_interviewer_aptitude", "sign", "Libra", "work_application",
       "Interviewer aptitude (source-described tendency).",
       "strength", "interviewer_aptitude",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_communicator_aptitude", "sign", "Libra", "communication",
       "Communicator aptitude (source-described tendency).",
       "strength", "communicator_ability",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_salesperson_aptitude", "sign", "Libra", "work_application",
       "Salesperson aptitude (source-described tendency).",
       "strength", "sales",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_dialogue_skill", "sign", "Libra", "communication",
       "Dialogue skill.",
       "strength", "dialogue_skill",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_compliment_skill", "sign", "Libra", "communication",
       "Compliment skill.",
       "strength", "compliments",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_compromise_skill", "sign", "Libra", "communication",
       "Compromise skill.",
       "strength", "compromise",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_beauty_of_words", "sign", "Libra", "communication",
       "Beauty of words.",
       "strength", "beauty_of_words",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_beautiful_handwriting", "sign", "Libra", "communication",
       "Beautiful handwriting.",
       "neutral", "beautiful_handwriting",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_humanities_aptitude", "sign", "Libra", "work_application",
       "Humanities aptitude (source-described tendency).",
       "strength", "humanities_aptitude",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_occupation_associations", "sign", "Libra", "source_specific",
       "Source-described occupation associations include presenter, consultant, lawyer, and politician; not career assignments.",
       "neutral", "occupation_associations",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_learning_dialogue", "sign", "Libra", "learning",
       "Learning through dialogue.",
       "strength", "dialogue_learning",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_learning_books", "sign", "Libra", "learning",
       "Learning through books.",
       "neutral", "book_learning",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_learning_contrasts", "sign", "Libra", "learning",
       "Learning through contrasts.",
       "strength", "contrast_learning",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_learning_two_sides", "sign", "Libra", "learning",
       "Learning through two sides / two aspects of a situation.",
       "strength", "two_sided_learning",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_motivation_attractive_people", "sign", "Libra", "learning",
       "Learning motivation: attractive/aesthetic people.",
       "neutral", "aesthetic_people_motivation",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_motivation_attractive_subject", "sign", "Libra", "learning",
       "Learning motivation: attractive subject/material.",
       "neutral", "attractive_subject_motivation",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_motivation_aesthetic_environment", "sign", "Libra", "learning",
       "Learning motivation: aesthetically pleasing learning environment.",
       "neutral", "aesthetic_environment_motivation",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_motivation_possibility_to_discuss", "sign", "Libra", "learning",
       "Learning motivation: possibility to discuss.",
       "neutral", "discussion_motivation",
       source_reference=REF_LIBRA_BIO),
    _f("libra_bio_motivation_establish_fairness", "sign", "Libra", "learning",
       "Learning motivation: possibility to establish fairness.",
       "neutral", "fairness_motivation",
       source_reference=REF_LIBRA_BIO),
)

LIBRA_AFFLICTED: tuple[SourceFactDef, ...] = (
    _f("libra_bio_afflicted_intellectual_indecision", "sign", "Libra", "risk",
       _AFFLICTED_PREFIX + "intellectual indecision.",
       "risk", "intellectual_indecision",
       source_reference=REF_LIBRA_BIO, activation_condition="hard_aspected"),
    _f("libra_bio_afflicted_absence_of_conclusions", "sign", "Libra", "risk",
       _AFFLICTED_PREFIX + "absence of conclusions.",
       "risk", "absence_of_conclusion",
       source_reference=REF_LIBRA_BIO, activation_condition="hard_aspected"),
    _f("libra_bio_afflicted_absence_of_position", "sign", "Libra", "risk",
       _AFFLICTED_PREFIX + "absence of a position.",
       "risk", "absence_of_position",
       source_reference=REF_LIBRA_BIO, activation_condition="hard_aspected"),
    _f("libra_bio_afflicted_lying_distortion", "sign", "Libra", "risk",
       _AFFLICTED_PREFIX + "lying / distortion tendency (source-described afflicted possibility, not a person accusation).",
       "risk", "lying_distortion",
       source_reference=REF_LIBRA_BIO, activation_condition="hard_aspected"),
    _f("libra_bio_afflicted_excessively_sugary_communication", "sign", "Libra", "risk",
       _AFFLICTED_PREFIX + "excessively sugary / forced-positive communication tendency.",
       "risk", "sugary_forced_positive_communication",
       source_reference=REF_LIBRA_BIO, activation_condition="hard_aspected"),
)

LIBRA_ALL: tuple[SourceFactDef, ...] = LIBRA_LESSON7 + LIBRA_BIOASTROLOGY + LIBRA_AFFLICTED

# ---------------------------------------------------------------------------
# Scorpio — Lesson 7
# ---------------------------------------------------------------------------
SCORPIO_LESSON7: tuple[SourceFactDef, ...] = (
    _f("scorpio_l7_categorical_thinking", "sign", "Scorpio", "thinking",
       "Categorical thinking.",
       "neutral", "categorical_thinking",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_maximalist_thinking", "sign", "Scorpio", "thinking",
       "Maximalist thinking.",
       "risk", "maximalist_thinking",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_very_deep_memory", "sign", "Scorpio", "memory",
       "Very deep memory.",
       "strength", "deep_memory",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_sticky_memory", "sign", "Scorpio", "memory",
       "Sticky memory.",
       "strength", "sticky_memory",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_high_analytical_ability", "sign", "Scorpio", "thinking",
       "High analytical ability.",
       "strength", "analytical_thinking",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_sensitivity_to_intuitive_impressions", "sign", "Scorpio", "thinking",
       "Sensitivity to intuitive impressions.",
       "neutral", "intuitive_impression_sensitivity",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_extraction_of_nonverbal_information", "sign", "Scorpio", "thinking",
       "Extraction of nonverbal information.",
       "strength", "nonverbal_information",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_depth", "sign", "Scorpio", "thinking",
       "Depth.",
       "strength", "depth",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_ability_to_see_the_essence", "sign", "Scorpio", "thinking",
       "Ability to see the essence.",
       "strength", "essence_detection",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_detective_like_thinking", "sign", "Scorpio", "thinking",
       "Detective-like thinking.",
       "strength", "detective_thinking",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_destroy_to_understand", "sign", "Scorpio", "thinking",
       "Destroy/deconstruct in order to understand.",
       "neutral", "deconstructive_understanding",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_research_oriented_mind", "sign", "Scorpio", "thinking",
       "Research-oriented mind.",
       "strength", "research_mind",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_tense_communication", "sign", "Scorpio", "communication",
       "Tense communication.",
       "risk", "tense_communication",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_caustic_speech", "sign", "Scorpio", "communication",
       "Caustic speech.",
       "risk", "caustic_speech",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_hints", "sign", "Scorpio", "communication",
       "Hints.",
       "neutral", "hints",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_verbal_jabs", "sign", "Scorpio", "communication",
       "Verbal jabs.",
       "risk", "verbal_jabs",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_sharp_replies", "sign", "Scorpio", "communication",
       "Sharp replies.",
       "risk", "sharp_reply",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_fast_replies", "sign", "Scorpio", "communication",
       "Fast replies.",
       "neutral", "fast_reply",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_many_probing_questions", "sign", "Scorpio", "communication",
       "Many probing questions.",
       "neutral", "probing_questions",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_tendency_to_dig_to_core", "sign", "Scorpio", "communication",
       "Tendency to dig to the core.",
       "strength", "dig_to_core",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_says_very_little_explicitly", "sign", "Scorpio", "communication",
       "Says very little explicitly.",
       "neutral", "sparse_explicit_speech",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_expects_listener_to_infer", "sign", "Scorpio", "communication",
       "Expects listener to infer the rest.",
       "neutral", "expects_listener_inference",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_dev_awareness_of_causticity", "sign", "Scorpio", "work_application",
       "Development focus: awareness of own causticity.",
       "neutral", "causticity_awareness",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_dev_awareness_of_criticality", "sign", "Scorpio", "work_application",
       "Development focus: awareness of own criticality.",
       "neutral", "criticality_awareness",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_dev_finish_explain_thought", "sign", "Scorpio", "work_application",
       "Development focus: learn to finish/explain the thought instead of cutting it off with hints.",
       "neutral", "finish_explain_thought",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_learn_dig_to_essence", "sign", "Scorpio", "learning",
       "Learning support: dig to essence.",
       "strength", "essence_learning",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_independent_learning", "sign", "Scorpio", "learning",
       "Independent learning.",
       "strength", "independent_learning",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_quiet_environment", "sign", "Scorpio", "learning",
       "Learning support: quiet environment.",
       "neutral", "quiet_learning_environment",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_practice_learning", "sign", "Scorpio", "learning",
       "Learning support: practice.",
       "strength", "practice_based_learning",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_vulnerability_error_detection", "sign", "Scorpio", "learning",
       "Learning support: vulnerability/error detection.",
       "strength", "vulnerability_detection",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_argument_dispute_learning", "sign", "Scorpio", "learning",
       "Learning support: argument/dispute as learning mechanism.",
       "neutral", "dispute_learning",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_asking_questions_to_expose_essence", "sign", "Scorpio", "learning",
       "Learning support: asking questions to expose essence.",
       "strength", "essence_questioning",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_deep_concepts", "sign", "Scorpio", "learning",
       "Learning support: deep concepts.",
       "neutral", "deep_concepts_learning",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_risk_maximalism_in_evaluations", "sign", "Scorpio", "risk",
       "Difficulty: maximalism in evaluations.",
       "risk", "evaluation_maximalism",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_risk_sharp_judgments", "sign", "Scorpio", "risk",
       "Difficulty: sharp judgments.",
       "risk", "sharp_judgments",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_env_manipulation_source_claim", "sign", "Scorpio", "environment",
       "Manipulation skill / tendency as a source claim (source-described tendency, not a person accusation).",
       "risk", "manipulation",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_env_transformative_role", "sign", "Scorpio", "environment",
       "Transformative role.",
       "neutral", "transformative_role",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_env_hidden_sibling_tension", "sign", "Scorpio", "environment",
       "Hidden sibling tension.",
       "risk", "hidden_sibling_tension",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_env_sibling_verbal_jabs", "sign", "Scorpio", "environment",
       "Sibling verbal jabs.",
       "risk", "sibling_verbal_jabs",
       source_reference=REF_SCORPIO_L7),
    _f("scorpio_l7_env_sibling_competition", "sign", "Scorpio", "environment",
       "Sibling competition.",
       "risk", "sibling_competition",
       source_reference=REF_SCORPIO_L7),
)

SCORPIO_BIOASTROLOGY: tuple[SourceFactDef, ...] = (
    _f("scorpio_bio_pluto_colored_framing", "sign", "Scorpio", "source_specific",
       "Pluto-colored thinking / learning / communication (source-specific framing, not a scientific statement).",
       "neutral", "pluto_colored_framing",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_critic_aptitude", "sign", "Scorpio", "work_application",
       "Critic aptitude (source-described tendency).",
       "strength", "critic_aptitude",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_analytical_aptitude", "sign", "Scorpio", "thinking",
       "Analytical aptitude (source-described tendency).",
       "strength", "analytical_thinking",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_researcher_aptitude", "sign", "Scorpio", "work_application",
       "Researcher aptitude (source-described tendency).",
       "strength", "research_mind",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_psychological_penetration", "sign", "Scorpio", "thinking",
       "Psychological penetration / probing.",
       "strength", "psychological_penetration",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_influence_people", "sign", "Scorpio", "communication",
       "Ability/tendency to influence people (source-described tendency).",
       "strength", "influence",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_technical_aptitude", "sign", "Scorpio", "work_application",
       "Technical aptitude (source-described tendency).",
       "strength", "technical_ability",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_sticky_attention", "sign", "Scorpio", "focus",
       "Sticky attention.",
       "strength", "sticky_attention",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_strong_memory", "sign", "Scorpio", "memory",
       "Strong memory.",
       "strength", "strong_memory",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_quiet_calm_voice", "sign", "Scorpio", "communication",
       "Quiet calm voice.",
       "neutral", "quiet_calm_voice",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_authoritative_voice_effect", "sign", "Scorpio", "communication",
       "Authoritative/commanding effect of voice as a source claim.",
       "neutral", "authoritative_voice_effect",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_intuitive_deep_thinking", "sign", "Scorpio", "thinking",
       "Intuitive deep thinking.",
       "strength", "intuitive_thinking",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_speak_through_secrets", "sign", "Scorpio", "communication",
       "Tendency to speak through secrets / \"figure it out yourself\".",
       "neutral", "secretive_speech",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_occupation_associations", "sign", "Scorpio", "source_specific",
       "Source-described occupation associations include manager, entrepreneur, and psychologist; not career assignments.",
       "neutral", "occupation_associations",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_learning_criticizing_others_ideas", "sign", "Scorpio", "learning",
       "Learning through criticizing / dismantling other people's ideas.",
       "neutral", "criticism_of_ideas_learning",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_learning_group_discussion", "sign", "Scorpio", "learning",
       "Learning through group discussion.",
       "neutral", "group_discussion_learning",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_learning_independent_research", "sign", "Scorpio", "learning",
       "Learning through independent research.",
       "strength", "independent_research_learning",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_motivation_challenge_prove", "sign", "Scorpio", "learning",
       "Learning motivation: challenge / \"prove you can\".",
       "neutral", "challenge_prove_motivation",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_motivation_curiosity", "sign", "Scorpio", "learning",
       "Learning motivation: curiosity.",
       "neutral", "curiosity_motivated_learning",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_motivation_influence_linked_info", "sign", "Scorpio", "learning",
       "Learning motivation: information linked to possibility of influence.",
       "neutral", "influence_linked_info_motivation",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_source_sexual_motivation", "sign", "Scorpio", "source_specific",
       "Source framework includes sexual motivation wording for learning drive; preserved as source wording only, not a professional/hiring recommendation.",
       "neutral", "source_sexual_motivation_wording",
       source_reference=REF_SCORPIO_BIO),
    _f("scorpio_bio_motivation_money", "sign", "Scorpio", "learning",
       "Learning motivation: money.",
       "neutral", "money_motivation",
       source_reference=REF_SCORPIO_BIO),
)

SCORPIO_AFFLICTED: tuple[SourceFactDef, ...] = (
    _f("scorpio_bio_afflicted_maximalism_in_evaluations", "sign", "Scorpio", "risk",
       _AFFLICTED_PREFIX + "maximalism in evaluations.",
       "risk", "evaluation_maximalism",
       source_reference=REF_SCORPIO_BIO, activation_condition="hard_aspected"),
    _f("scorpio_bio_afflicted_quarrelsome_verbal_conflict", "sign", "Scorpio", "risk",
       _AFFLICTED_PREFIX + "quarrelsome/abusive verbal conflict.",
       "risk", "quarrelsome_verbal_conflict",
       source_reference=REF_SCORPIO_BIO, activation_condition="hard_aspected"),
    _f("scorpio_bio_afflicted_mockery_malicious_wit", "sign", "Scorpio", "risk",
       _AFFLICTED_PREFIX + "mockery / malicious wit / snide communication.",
       "risk", "mockery_malicious_wit",
       source_reference=REF_SCORPIO_BIO, activation_condition="hard_aspected"),
    _f("scorpio_bio_afflicted_causticity", "sign", "Scorpio", "risk",
       _AFFLICTED_PREFIX + "causticity.",
       "risk", "causticity",
       source_reference=REF_SCORPIO_BIO, activation_condition="hard_aspected"),
)

SCORPIO_ALL: tuple[SourceFactDef, ...] = SCORPIO_LESSON7 + SCORPIO_BIOASTROLOGY + SCORPIO_AFFLICTED

A2_SIGN_PACKS: tuple[SourceFactDef, ...] = VIRGO_ALL + LIBRA_ALL + SCORPIO_ALL
