"""Static Bioastrology/methodology source facts for Mercury Source Profile v2.

v2 coverage includes golden cases:
- Avdey: Leo, House 1, Retrograde, square Pluto, trine Saturn, sextile Moon
- Vlad: Taurus, House 9, square Moon, trine Mars, sextile Jupiter
- Dzmitry: Sagittarius, House 10, sextile Mars, sextile Jupiter, conjunction Uranus

Sign Batch A1 dual-source packs (Lesson 7 + Bioastrology):
- Aries, Gemini, Cancer
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class SourceFactDef:
    id: str
    factor_type: str
    factor_key: str
    category: str
    text: str
    polarity: str
    tags: tuple[str, ...] = ()
    source_reference: str = ""
    activation_condition: str | None = None
    unresolved: bool = False


def _f(
    id: str,
    factor_type: str,
    factor_key: str,
    category: str,
    text: str,
    polarity: str,
    *tags: str,
    source_reference: str,
    activation_condition: str | None = None,
    unresolved: bool = False,
) -> SourceFactDef:
    return SourceFactDef(
        id=id,
        factor_type=factor_type,
        factor_key=factor_key,
        category=category,
        text=text,
        polarity=polarity,
        tags=tags,
        source_reference=source_reference,
        activation_condition=activation_condition,
        unresolved=unresolved,
    )


REF_LEO = "bioastrology_mercury_leo"
REF_H1 = "bioastrology_mercury_house_1"
REF_RX = "methodology_mercury_retrograde"
REF_PLUTO_SQ = "bioastrology_mercury_pluto_square"
REF_SATURN_HARM = "bioastrology_mercury_saturn_harmonious"
REF_MOON_HARM = "bioastrology_mercury_moon_harmonious"
REF_TAURUS = "lesson7_mercury_taurus"
REF_H9 = "lesson7_mercury_house_9"
REF_MOON_SQ = "lesson7_mercury_moon_square"
REF_MARS_HARM = "bioastrology_mercury_mars_harmonious"
REF_JUPITER_HARM = "bioastrology_mercury_jupiter_harmonious"
REF_SAGITTARIUS = "lesson7_mercury_sagittarius"
REF_H10 = "lesson7_mercury_house_10"
REF_URANUS_CONJ = "bioastrology_mercury_uranus_conjunction"

# ---------------------------------------------------------------------------
# Mercury in Leo — general
# ---------------------------------------------------------------------------
LEO_GENERAL: tuple[SourceFactDef, ...] = (
    _f("leo_expressive_visible_thinking", "sign", "Leo", "thinking",
       "Thinking, communication and learning are highly expressive, solar and visible.",
       "neutral", "expressive", "visible_communication",
       source_reference=REF_LEO),
    _f("leo_strong_creative_quality", "sign", "Leo", "thinking",
       "Strong creative quality in thinking and expression.",
       "strength", "creative",
       source_reference=REF_LEO),
    _f("leo_strong_debate_potential", "sign", "Leo", "communication",
       "Very strong debate potential.",
       "strength", "debate",
       source_reference=REF_LEO),
    _f("leo_risk_intellectual_superficiality", "sign", "Leo", "risk",
       "Risk of intellectual superficiality and intellectual primitiveness.",
       "risk", "superficiality", "primitiveness",
       source_reference=REF_LEO),
    _f("leo_thinks_from_own_position", "sign", "Leo", "thinking",
       "Tends to think from one's own position rather than from others' frames.",
       "neutral", "self_centered_thinking",
       source_reference=REF_LEO),
    _f("leo_may_discount_others_opinions", "sign", "Leo", "communication",
       "May discount other people's opinions.",
       "risk", "stubbornness", "self_centered_thinking",
       source_reference=REF_LEO),
    _f("leo_dialogue_difficulty", "sign", "Leo", "communication",
       "This can make real two-way dialogue difficult.",
       "risk", "dialogue_friction",
       source_reference=REF_LEO),
    _f("leo_nonstandard_speech_thinking", "sign", "Leo", "communication",
       "Nonstandard speech and thinking.",
       "strength", "nonstandard_thinking",
       source_reference=REF_LEO),
    _f("leo_strong_oratory_potential", "sign", "Leo", "communication",
       "Strong oratory potential.",
       "strength", "oratory", "presentation",
       source_reference=REF_LEO),
    _f("leo_leadership_communication_potential", "sign", "Leo", "communication",
       "Leadership communication potential.",
       "strength", "presentation", "leadership_communication",
       source_reference=REF_LEO),
    _f("leo_pr_ability", "sign", "Leo", "work_application",
       "PR ability.",
       "strength", "presentation",
       source_reference=REF_LEO),
    _f("leo_sales_ability", "sign", "Leo", "work_application",
       "Sales ability.",
       "strength", "sales", "persuasion",
       source_reference=REF_LEO),
    _f("leo_learns_through_impressions", "sign", "Leo", "learning",
       "Learns well through impressions.",
       "neutral", "learning_style",
       source_reference=REF_LEO),
    _f("leo_learns_through_independent_investigation", "sign", "Leo", "learning",
       "Learns through independent investigation and digging into material.",
       "strength", "independent_learning", "nonstandard_learning",
       source_reference=REF_LEO),
    _f("leo_wants_to_demonstrate_results", "sign", "Leo", "learning",
       "Wants to later demonstrate intellectual results to others.",
       "neutral", "visible_communication",
       source_reference=REF_LEO),
    _f("leo_praise_motivates_learning", "sign", "Leo", "learning",
       "Praise can motivate learning.",
       "neutral", "learning_motivation",
       source_reference=REF_LEO),
    _f("leo_playful_competition_motivates_learning", "sign", "Leo", "learning",
       "Game or playful competition can motivate learning.",
       "neutral", "learning_motivation",
       source_reference=REF_LEO),
    _f("leo_visible_status_motivates_learning", "sign", "Leo", "learning",
       "Visible status or attractive reward can motivate learning.",
       "neutral", "learning_motivation",
       source_reference=REF_LEO),
)

# Afflicted Mercury in Leo — only when hard_aspected
LEO_AFFLICTED: tuple[SourceFactDef, ...] = (
    _f("leo_afflicted_putting_on_a_show", "sign", "Leo", "risk",
       "Putting on a show / throwing dust in people's eyes.",
       "risk", "misleading_presentation", "appearance_of_competence",
       source_reference=REF_LEO, activation_condition="hard_aspected"),
    _f("leo_afflicted_lying_distortion", "sign", "Leo", "risk",
       "Lying / distortion / misrepresentation.",
       "risk", "lying_distortion", "misleading_presentation",
       source_reference=REF_LEO, activation_condition="hard_aspected"),
    _f("leo_afflicted_appearance_of_competence", "sign", "Leo", "risk",
       "Appearance of competence instead of real professionalism.",
       "risk", "appearance_of_competence", "misleading_presentation",
       source_reference=REF_LEO, activation_condition="hard_aspected"),
    _f("leo_afflicted_superior_manner", "sign", "Leo", "communication",
       "Superior / lordly communication manner.",
       "risk", "superior_manner",
       source_reference=REF_LEO, activation_condition="hard_aspected"),
    _f("leo_afflicted_expecting_admiration", "sign", "Leo", "communication",
       "Expecting admiration / applause.",
       "risk", "expecting_admiration",
       source_reference=REF_LEO, activation_condition="hard_aspected"),
    _f("leo_afflicted_extreme_stubbornness", "sign", "Leo", "thinking",
       "Extreme stubbornness in thinking.",
       "risk", "stubbornness",
       source_reference=REF_LEO, activation_condition="hard_aspected"),
    _f("leo_afflicted_ego_interferes_with_facts", "sign", "Leo", "thinking",
       "Ego interfering with objective perception of facts.",
       "risk", "ego_interference", "stubbornness",
       source_reference=REF_LEO, activation_condition="hard_aspected"),
)

# ---------------------------------------------------------------------------
# Mercury in House 1
# ---------------------------------------------------------------------------
HOUSE_1: tuple[SourceFactDef, ...] = (
    _f("h1_strengthens_mercury_functions", "house", "1", "thinking",
       "Strengthens Mercury functions overall.",
       "strength", "amplifier",
       source_reference=REF_H1),
    _f("h1_emphasizes_mercury_sign", "house", "1", "thinking",
       "Emphasizes the Mercury sign.",
       "neutral", "amplifier", "sign_emphasis",
       source_reference=REF_H1),
    _f("h1_emphasizes_mercury_aspects", "house", "1", "thinking",
       "Emphasizes Mercury aspects.",
       "neutral", "amplifier", "aspect_emphasis",
       source_reference=REF_H1),
    _f("h1_youthful_quality", "house", "1", "communication",
       "Youthful quality.",
       "neutral", "youthful",
       source_reference=REF_H1),
    _f("h1_outward_friendliness", "house", "1", "communication",
       "Outward friendliness / openness.",
       "strength", "openness",
       source_reference=REF_H1),
    _f("h1_increased_learnability", "house", "1", "learning",
       "Increased learnability.",
       "strength", "learnability",
       source_reference=REF_H1),
    _f("h1_quickness", "house", "1", "thinking",
       "Quickness.",
       "strength", "quickness",
       source_reference=REF_H1),
    _f("h1_multitasking", "house", "1", "thinking",
       "Multitasking.",
       "strength", "multitasking",
       source_reference=REF_H1),
    _f("h1_talkative_or_writing_tendency", "house", "1", "communication",
       "Increased talkativeness and increased writing tendency.",
       "neutral", "talkative", "writing",
       source_reference=REF_H1),
    _f("h1_special_relevance_siblings", "house", "1", "environment",
       "Special relevance of siblings.",
       "neutral", "siblings",
       source_reference=REF_H1),
    _f("h1_special_relevance_car_driving", "house", "1", "mobility",
       "Special relevance of car / driving.",
       "neutral", "driving", "mobility",
       source_reference=REF_H1),
    _f("h1_eventfulness_books", "house", "1", "environment",
       "Increased eventfulness connected with books.",
       "neutral", "books",
       source_reference=REF_H1),
    _f("h1_eventfulness_trips", "house", "1", "mobility",
       "Increased eventfulness connected with trips.",
       "neutral", "trips", "mobility",
       source_reference=REF_H1),
    _f("h1_eventfulness_social_networks", "house", "1", "environment",
       "Increased eventfulness connected with social networks.",
       "neutral", "social_networks",
       source_reference=REF_H1),
    _f("h1_support_intellectual_work", "house", "1", "work_application",
       "Support for intellectual profession and transport-related profession.",
       "strength", "intellectual_work", "transport_profession",
       source_reference=REF_H1),
    _f("h1_support_consultant_qualities", "house", "1", "work_application",
       "Support for consultant qualities.",
       "strength", "consulting",
       source_reference=REF_H1),
    _f("h1_support_sales_qualities", "house", "1", "work_application",
       "Support for sales qualities.",
       "strength", "sales",
       source_reference=REF_H1),
)

# ---------------------------------------------------------------------------
# Retrograde Mercury
# ---------------------------------------------------------------------------
RETROGRADE: tuple[SourceFactDef, ...] = (
    _f("rx_works_more_inwardly", "motion", "retrograde", "thinking",
       "Mercury function works more inwardly.",
       "neutral", "inward_processing",
       source_reference=REF_RX),
    _f("rx_communication_learning_unusual", "motion", "retrograde", "communication",
       "Communication / learning may function unusually.",
       "neutral", "nonstandard_learning",
       source_reference=REF_RX),
    _f("rx_processing_takes_longer", "motion", "retrograde", "learning",
       "Processing can take longer.",
       "neutral", "relearning", "inward_processing",
       source_reference=REF_RX),
    _f("rx_repeated_internal_processing", "motion", "retrograde", "learning",
       "Information may require repeated internal processing.",
       "neutral", "relearning", "inward_processing",
       source_reference=REF_RX),
    _f("rx_nonstandard_solutions", "motion", "retrograde", "thinking",
       "Can find nonstandard solutions.",
       "strength", "nonstandard_thinking",
       source_reference=REF_RX),
    _f("rx_unexpected_conclusions", "motion", "retrograde", "thinking",
       "Can arrive at unexpected conclusions.",
       "strength", "nonstandard_thinking",
       source_reference=REF_RX),
    _f("rx_tendency_to_relearn", "motion", "retrograde", "learning",
       "Tendency to relearn.",
       "neutral", "relearning",
       source_reference=REF_RX),
    _f("rx_tendency_to_rewrite", "motion", "retrograde", "learning",
       "Tendency to rewrite.",
       "neutral", "relearning", "writing",
       source_reference=REF_RX),
    _f("rx_revisit_previously_learned", "motion", "retrograde", "learning",
       "Tendency to revisit previously learned material.",
       "neutral", "relearning",
       source_reference=REF_RX),
    _f("rx_written_easier_than_spontaneous", "motion", "retrograde", "communication",
       "Written expression may sometimes be easier than immediate spontaneous speaking.",
       "neutral", "writing",
       source_reference=REF_RX),
)

# ---------------------------------------------------------------------------
# Mercury square Pluto
# ---------------------------------------------------------------------------
PLUTO_SQUARE: tuple[SourceFactDef, ...] = (
    _f("pluto_sq_core_conflict", "aspect", "square_Pluto", "thinking",
       "Mercury thinking/communication/learning is in strong conflict with Pluto intensity, power, destruction and depth.",
       "risk", "conflict", "depth",
       source_reference=REF_PLUTO_SQ),
    # Unresolved strength branches — both returned; neither selected.
    _f("pluto_sq_branch_mercury_stronger_primitive_thinking", "aspect", "square_Pluto", "thinking",
       "When Mercury dominates this square: primitive / degraded thinking.",
       "conditional", "primitiveness", "conflict",
       source_reference=REF_PLUTO_SQ,
       activation_condition="pluto_strength_unresolved", unresolved=True),
    _f("pluto_sq_branch_mercury_stronger_quarrelsomeness", "aspect", "square_Pluto", "communication",
       "When Mercury dominates this square: quarrelsomeness.",
       "conditional", "conflict",
       source_reference=REF_PLUTO_SQ,
       activation_condition="pluto_strength_unresolved", unresolved=True),
    _f("pluto_sq_branch_mercury_stronger_damaged_intellect", "aspect", "square_Pluto", "thinking",
       "When Mercury dominates this square: intellectual function behaving as if damaged or disrupted.",
       "conditional", "primitiveness", "conflict",
       source_reference=REF_PLUTO_SQ,
       activation_condition="pluto_strength_unresolved", unresolved=True),
    _f("pluto_sq_branch_mercury_stronger_armchair_grandiosity", "aspect", "square_Pluto", "thinking",
       "When Mercury dominates this square: tendency toward armchair grandiosity / pseudo-philosophizing.",
       "conditional", "primitiveness",
       source_reference=REF_PLUTO_SQ,
       activation_condition="pluto_strength_unresolved", unresolved=True),
    _f("pluto_sq_branch_pluto_stronger_super_will", "aspect", "square_Pluto", "thinking",
       "When Pluto dominates this square: very strong will / super-will.",
       "conditional", "depth",
       source_reference=REF_PLUTO_SQ,
       activation_condition="pluto_strength_unresolved", unresolved=True),
    _f("pluto_sq_branch_pluto_stronger_energetic_depth", "aspect", "square_Pluto", "thinking",
       "When Pluto dominates this square: extreme energetic depth.",
       "conditional", "depth",
       source_reference=REF_PLUTO_SQ,
       activation_condition="pluto_strength_unresolved", unresolved=True),
    _f("pluto_sq_branch_pluto_stronger_penetrates_mercury", "aspect", "square_Pluto", "thinking",
       "When Pluto dominates this square: Pluto intensity penetrates Mercury thinking / learning very deeply.",
       "conditional", "depth",
       source_reference=REF_PLUTO_SQ,
       activation_condition="pluto_strength_unresolved", unresolved=True),
    _f("pluto_sq_conflictual_communication", "aspect", "square_Pluto", "communication",
       "Toxic conflictual atmosphere around communication.",
       "risk", "conflict",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_aggressive_driving_accident_risk", "aspect", "square_Pluto", "mobility",
       "Aggressive-driving / accident risk signal.",
       "risk", "driving",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_neighbors_siblings_problems", "aspect", "square_Pluto", "environment",
       "Problems involving neighbors or siblings.",
       "risk", "siblings",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_trip_crises", "aspect", "square_Pluto", "mobility",
       "Crises / complications around trips.",
       "risk", "trips",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_dangerous_curiosity", "aspect", "square_Pluto", "thinking",
       "Dangerous curiosity.",
       "risk", "curiosity", "depth",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_pessimistic_fatalistic_tone", "aspect", "square_Pluto", "communication",
       "Pessimistic / fatalistic tone.",
       "risk", "pessimism",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_extremely_sharp_speech", "aspect", "square_Pluto", "communication",
       "Razor-sharp speech with poisonous / venomous quality and high potential to hurt through words.",
       "risk", "sharp_speech", "hurtful_speech",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_words_can_hurt", "aspect", "square_Pluto", "communication",
       "Words can strongly hurt / have high resonance.",
       "risk", "sharp_speech", "hurtful_speech",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_sarcasm", "aspect", "square_Pluto", "communication",
       "Sarcasm.",
       "neutral", "sarcasm", "sharp_speech",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_strong_sense_of_humor", "aspect", "square_Pluto", "communication",
       "Strong sense of humor.",
       "strength", "humor",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_destroy_dig_defeat_through_speech", "aspect", "square_Pluto", "communication",
       "Tendency to destroy / dig / defeat through thinking and speech.",
       "risk", "conflict", "sharp_speech",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_strong_persuasiveness", "aspect", "square_Pluto", "communication",
       "Strong persuasiveness.",
       "strength", "persuasion",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_strong_insight", "aspect", "square_Pluto", "thinking",
       "Strong insight.",
       "strength", "insight", "read_between_lines",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_powerful_words", "aspect", "square_Pluto", "communication",
       "Powerful words.",
       "strength", "persuasion", "sharp_speech",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_speak_uncomfortable_truth", "aspect", "square_Pluto", "communication",
       "Ability to speak uncomfortable truth directly.",
       "strength", "insight",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_debate_ability", "aspect", "square_Pluto", "communication",
       "Debate ability.",
       "strength", "debate",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_find_strong_arguments", "aspect", "square_Pluto", "communication",
       "Ability to find strong arguments.",
       "strength", "argumentation",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_technical_talent", "aspect", "square_Pluto", "work_application",
       "Technical talent.",
       "strength", "technical_ability",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_diagnose_problems", "aspect", "square_Pluto", "work_application",
       "Ability to diagnose problems.",
       "strength", "analytical_thinking", "vulnerability_detection",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_identify_vulnerabilities", "aspect", "square_Pluto", "work_application",
       "Ability to identify vulnerabilities.",
       "strength", "vulnerability_detection", "insight",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_analytical_ability", "aspect", "square_Pluto", "thinking",
       "Analytical ability.",
       "strength", "analytical_thinking",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_psychological_insight", "aspect", "square_Pluto", "thinking",
       "Psychological insight.",
       "strength", "insight", "read_between_lines",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_penetrate_hack_systems", "aspect", "square_Pluto", "work_application",
       "Ability to penetrate / \"hack\" systems.",
       "strength", "vulnerability_detection", "technical_ability", "insight",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_understand_weaknesses_in_reasoning", "aspect", "square_Pluto", "thinking",
       "Ability to understand weaknesses in another person's reasoning.",
       "strength", "vulnerability_detection", "analytical_thinking",
       source_reference=REF_PLUTO_SQ),
    _f("pluto_sq_fast_learning_through_criticism", "aspect", "square_Pluto", "learning",
       "Fast learning through criticism of existing concepts / systems.",
       "strength", "nonstandard_learning", "analytical_thinking", "independent_learning",
       source_reference=REF_PLUTO_SQ),
)

# ---------------------------------------------------------------------------
# Mercury trine Saturn
# ---------------------------------------------------------------------------
SATURN_TRINE: tuple[SourceFactDef, ...] = (
    _f("saturn_tr_works_with_maturity", "aspect", "trine_Saturn", "thinking",
       "Thinking / learning / communication works naturally with maturity.",
       "strength", "maturity", "discipline",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_long_term_orientation", "aspect", "trine_Saturn", "thinking",
       "Long-term orientation.",
       "strength", "planning", "discipline",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_patience", "aspect", "trine_Saturn", "thinking",
       "Patience.",
       "strength", "focus", "discipline",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_work_discipline", "aspect", "trine_Saturn", "work_application",
       "Work / discipline.",
       "strength", "discipline",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_analytical_ability", "aspect", "trine_Saturn", "thinking",
       "Analytical ability.",
       "strength", "analytical_thinking",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_technical_ability", "aspect", "trine_Saturn", "work_application",
       "Technical ability.",
       "strength", "technical_ability",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_strong_sticky_memory", "aspect", "trine_Saturn", "memory",
       "Strong / sticky memory.",
       "strength", "memory",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_long_mental_focus", "aspect", "trine_Saturn", "focus",
       "Ability to maintain mental focus for a long time.",
       "strength", "focus",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_organization", "aspect", "trine_Saturn", "work_application",
       "Organization.",
       "strength", "planning", "discipline",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_planning", "aspect", "trine_Saturn", "work_application",
       "Planning.",
       "strength", "planning",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_forecasting", "aspect", "trine_Saturn", "work_application",
       "Forecasting.",
       "strength", "planning",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_clear_structured_speech", "aspect", "trine_Saturn", "communication",
       "Clear structured speech.",
       "strength", "structured_speech",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_speak_point_by_point", "aspect", "trine_Saturn", "communication",
       "Ability to speak point-by-point.",
       "strength", "structured_speech",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_articulation", "aspect", "trine_Saturn", "communication",
       "Articulation.",
       "strength", "structured_speech",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_strong_logic", "aspect", "trine_Saturn", "thinking",
       "Strong logic.",
       "strength", "analytical_thinking",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_strong_argumentation", "aspect", "trine_Saturn", "communication",
       "Strong argumentation.",
       "strength", "argumentation",
       source_reference=REF_SATURN_HARM),
    _f("saturn_tr_driving_skill", "aspect", "trine_Saturn", "mobility",
       "Driving skill / ability to absorb rules and understand traffic flow.",
       "strength", "driving",
       source_reference=REF_SATURN_HARM),
)

# ---------------------------------------------------------------------------
# Mercury sextile Moon
# ---------------------------------------------------------------------------
MOON_SEXTILE: tuple[SourceFactDef, ...] = (
    _f("moon_sx_rational_mind_more_alive", "aspect", "sextile_Moon", "thinking",
       "Rational mind becomes more alive.",
       "strength", "insight",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_increased_insight", "aspect", "sextile_Moon", "thinking",
       "Increased insight.",
       "strength", "insight", "read_between_lines",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_sensitivity_to_partner", "aspect", "sextile_Moon", "communication",
       "Increased sensitivity to the conversation partner.",
       "strength", "read_between_lines",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_intuition", "aspect", "sextile_Moon", "thinking",
       "Intuition.",
       "strength", "insight", "read_between_lines",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_read_between_lines", "aspect", "sextile_Moon", "thinking",
       "Ability to read between the lines.",
       "strength", "read_between_lines", "insight",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_inspiration_muse", "aspect", "sextile_Moon", "thinking",
       "Connection to inspiration / muse.",
       "strength", "creative",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_emotional_background_processed", "aspect", "sextile_Moon", "thinking",
       "Emotional background becomes more mobile and mentally processed.",
       "neutral", "insight",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_relevance_of_trips", "aspect", "sextile_Moon", "mobility",
       "Increased relevance of trips.",
       "neutral", "trips",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_blogs", "aspect", "sextile_Moon", "communication",
       "Blogs.",
       "neutral", "writing", "social_networks",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_books", "aspect", "sextile_Moon", "learning",
       "Books.",
       "neutral", "books",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_many_friendly_connections", "aspect", "sextile_Moon", "environment",
       "Many friendly connections.",
       "strength", "openness",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_continuous_learning", "aspect", "sextile_Moon", "learning",
       "Continuous learning.",
       "strength", "independent_learning",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_writing_ability", "aspect", "sextile_Moon", "communication",
       "Writing ability.",
       "strength", "writing",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_poetic_ability", "aspect", "sextile_Moon", "communication",
       "Poetic ability.",
       "strength", "writing", "creative",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_strong_sticky_memory", "aspect", "sextile_Moon", "memory",
       "Strong / sticky memory.",
       "strength", "memory",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_softer_melodic_speech", "aspect", "sextile_Moon", "communication",
       "Softer / melodic spoken language.",
       "strength", "soft_speech",
       source_reference=REF_MOON_HARM),
    _f("moon_sx_dexterity", "aspect", "sextile_Moon", "work_application",
       "Dexterity.",
       "strength", "dexterity",
       source_reference=REF_MOON_HARM),
)

# ---------------------------------------------------------------------------
# Mercury in Taurus (Vlad)
# ---------------------------------------------------------------------------
TAURUS_GENERAL: tuple[SourceFactDef, ...] = (
    _f("taurus_productive_thinking", "sign", "Taurus", "thinking",
       "Productive thinking.",
       "strength", "practical_fact_based",
       source_reference=REF_TAURUS),
    _f("taurus_harmonious_thinking", "sign", "Taurus", "thinking",
       "Harmonious thinking.",
       "strength", "deliberate_processing",
       source_reference=REF_TAURUS),
    _f("taurus_unhurried_thinking", "sign", "Taurus", "thinking",
       "Unhurried thinking.",
       "strength", "deliberate_processing",
       source_reference=REF_TAURUS),
    _f("taurus_thorough_thinking", "sign", "Taurus", "thinking",
       "Thorough thinking.",
       "strength", "deliberate_processing", "practical_fact_based",
       source_reference=REF_TAURUS),
    _f("taurus_slow_processing_long_retention", "sign", "Taurus", "learning",
       "Processes slowly but retains learned material for a long time.",
       "neutral", "deliberate_processing", "long_retention",
       source_reference=REF_TAURUS),
    _f("taurus_practical_concrete_orientation", "sign", "Taurus", "thinking",
       "Practical / concrete orientation.",
       "strength", "practical_fact_based",
       source_reference=REF_TAURUS),
    _f("taurus_relies_on_common_sense", "sign", "Taurus", "thinking",
       "Relies on common sense.",
       "strength", "practical_fact_based",
       source_reference=REF_TAURUS),
    _f("taurus_values_factual_reliability", "sign", "Taurus", "thinking",
       "Values factual reliability.",
       "strength", "practical_fact_based",
       source_reference=REF_TAURUS),
    _f("taurus_may_recheck_information", "sign", "Taurus", "learning",
       "May re-check information.",
       "neutral", "practical_fact_based", "deliberate_processing",
       source_reference=REF_TAURUS),
    _f("taurus_abstraction_harder_than_concrete", "sign", "Taurus", "learning",
       "Abstraction can be harder than concrete / practical material.",
       "risk", "practical_fact_based",
       source_reference=REF_TAURUS),
    _f("taurus_measured_orderly_speech", "sign", "Taurus", "communication",
       "Measured, orderly speech.",
       "strength", "structured_communication", "deliberate_processing",
       source_reference=REF_TAURUS),
    _f("taurus_clearly_structured_speech", "sign", "Taurus", "communication",
       "Speech tends to be clearly structured.",
       "strength", "structured_communication",
       source_reference=REF_TAURUS),
    _f("taurus_thinks_before_speaking", "sign", "Taurus", "communication",
       "Tends to think before speaking.",
       "strength", "deliberate_processing", "structured_communication",
       source_reference=REF_TAURUS),
    _f("taurus_conversation_needs_practical_purpose", "sign", "Taurus", "communication",
       "Conversation should have a practical / result-oriented purpose.",
       "neutral", "practical_fact_based",
       source_reference=REF_TAURUS),
    _f("taurus_calm_authoritative_communication", "sign", "Taurus", "communication",
       "Calm / authoritative communication style.",
       "strength", "structured_communication",
       source_reference=REF_TAURUS),
    _f("taurus_learning_needs_time_without_pressure", "sign", "Taurus", "learning",
       "Needs enough time to process; pressure interferes with this learning style.",
       "neutral", "deliberate_processing", "learning_through_application",
       source_reference=REF_TAURUS),
    _f("taurus_learning_repetition_persistence", "sign", "Taurus", "learning",
       "Repetition and persistence support learning.",
       "strength", "long_retention", "learning_through_application",
       source_reference=REF_TAURUS),
    _f("taurus_comfortable_learning_environment", "sign", "Taurus", "learning",
       "Comfortable learning environment supports learning.",
       "neutral", "learning_through_application",
       source_reference=REF_TAURUS),
    _f("taurus_tangible_benefit_motivates_learning", "sign", "Taurus", "learning",
       "Tangible benefit / practical motivation supports learning.",
       "neutral", "practical_fact_based", "learning_through_application",
       source_reference=REF_TAURUS),
    _f("taurus_applying_knowledge_in_practice", "sign", "Taurus", "learning",
       "Applying knowledge in practice supports learning.",
       "strength", "learning_through_application", "practical_fact_based",
       source_reference=REF_TAURUS),
    _f("taurus_risk_inertia", "sign", "Taurus", "risk",
       "Risk of inertia.",
       "risk", "deliberate_processing",
       source_reference=REF_TAURUS),
    _f("taurus_slower_switching_topics", "sign", "Taurus", "risk",
       "Slower switching between topics / tasks.",
       "risk", "deliberate_processing",
       source_reference=REF_TAURUS),
    _f("taurus_difficulty_rapidly_changing_mental_direction", "sign", "Taurus", "risk",
       "Difficulty rapidly changing mental direction.",
       "risk", "deliberate_processing",
       source_reference=REF_TAURUS),
)

# ---------------------------------------------------------------------------
# Mercury in House 9 (Vlad)
# ---------------------------------------------------------------------------
HOUSE_9: tuple[SourceFactDef, ...] = (
    _f("h9_filters_significant_information", "house", "9", "thinking",
       "Filters significant information from a larger information stream.",
       "strength", "information_filtering",
       source_reference=REF_H9),
    _f("h9_analytical_with_abstract", "house", "9", "thinking",
       "Analytical thinking works together with abstract thinking.",
       "strength", "analytical_plus_abstract", "analytical_thinking", "abstract_thinking",
       source_reference=REF_H9),
    _f("h9_interest_other_cultures", "house", "9", "environment",
       "Understanding / interest in other cultures.",
       "strength", "other_cultures",
       source_reference=REF_H9),
    _f("h9_interest_geography_travel", "house", "9", "mobility",
       "Interest in geography and travel.",
       "neutral", "geography_travel",
       source_reference=REF_H9),
    _f("h9_attraction_to_sciences", "house", "9", "learning",
       "Attraction to sciences.",
       "strength", "science_interest", "broad_knowledge_orientation",
       source_reference=REF_H9),
    _f("h9_multiple_educations", "house", "9", "learning",
       "Multiple educations / repeated formal learning may occur.",
       "neutral", "lifelong_learning",
       source_reference=REF_H9),
    _f("h9_interest_foreign_languages", "house", "9", "learning",
       "Interest in foreign languages.",
       "strength", "foreign_languages",
       source_reference=REF_H9),
    _f("h9_eternal_student", "house", "9", "learning",
       "\"Eternal student\": circumstances require continued learning.",
       "neutral", "lifelong_learning",
       source_reference=REF_H9),
    _f("h9_elevates_intellectual_social_level", "house", "9", "environment",
       "The house can elevate intellectual / social level over time.",
       "strength", "status_elevation",
       source_reference=REF_H9),
    _f("h9_casual_communication_less_natural", "house", "9", "communication",
       "Casual / simple communication may be less natural; communication can become formal or etiquette-conscious.",
       "risk", "structured_communication",
       source_reference=REF_H9),
    _f("h9_need_to_monitor_speech", "house", "9", "communication",
       "May feel a need to monitor speech.",
       "risk", "structured_communication",
       source_reference=REF_H9),
    _f("h9_selective_communication", "house", "9", "communication",
       "Selective communication / preference for selected circles.",
       "neutral", "information_filtering",
       source_reference=REF_H9),
    _f("h9_consume_too_much_high_level_info", "house", "9", "risk",
       "May consume too much high-level information.",
       "risk", "information_filtering",
       source_reference=REF_H9),
    _f("h9_cycle_on_unnecessary_information", "house", "9", "risk",
       "May cycle on unnecessary or excessive information.",
       "risk", "information_filtering",
       source_reference=REF_H9),
    _f("h9_needs_argumentation_evidence", "house", "9", "thinking",
       "Does not readily accept an idea without argumentation / evidence.",
       "neutral", "evidence_requirement",
       source_reference=REF_H9),
    _f("h9_status_environment_mismatch", "house", "9", "environment",
       "Possible feeling of being intellectually / socially out of place in a higher-status environment.",
       "risk", "status_environment_mismatch",
       source_reference=REF_H9),
)

# ---------------------------------------------------------------------------
# Mercury square Moon (Vlad)
# ---------------------------------------------------------------------------
MOON_SQUARE: tuple[SourceFactDef, ...] = (
    _f("moon_sq_emotion_rational_conflict", "aspect", "square_Moon", "thinking",
       "Emotional impressions and rational / verbal processing can conflict.",
       "risk", "emotion_cognition_tension",
       source_reference=REF_MOON_SQ),
    _f("moon_sq_felt_and_thought_may_diverge", "aspect", "square_Moon", "communication",
       "What is felt and what is thought / said may diverge.",
       "risk", "emotion_cognition_tension", "verbalizing_feelings_difficulty",
       source_reference=REF_MOON_SQ),
    _f("moon_sq_difficulty_translating_feelings", "aspect", "square_Moon", "communication",
       "Difficulty translating feelings into clear thought or language.",
       "risk", "verbalizing_feelings_difficulty", "emotion_cognition_tension",
       source_reference=REF_MOON_SQ),
    _f("moon_sq_difficulty_understanding_feelings", "aspect", "square_Moon", "thinking",
       "Difficulty understanding what one actually feels.",
       "risk", "emotion_cognition_tension",
       source_reference=REF_MOON_SQ),
    _f("moon_sq_emotion_disrupts_stable_processing", "aspect", "square_Moon", "thinking",
       "Emotional input can disrupt otherwise stable mental processing.",
       "risk", "emotion_cognition_tension", "mental_switching_pressure",
       source_reference=REF_MOON_SQ),
    _f("moon_sq_shifts_between_impressions", "aspect", "square_Moon", "thinking",
       "May shift between impressions before fully processing them.",
       "risk", "mental_switching_pressure", "emotion_cognition_tension",
       source_reference=REF_MOON_SQ),
    _f("moon_sq_moves_despite_fixation_need", "aspect", "square_Moon", "thinking",
       "Tendency to move between impressions even when the emotional nature itself seeks fixation / depth.",
       "risk", "mental_switching_pressure", "emotion_cognition_tension",
       source_reference=REF_MOON_SQ),
)

# ---------------------------------------------------------------------------
# Mercury trine Mars (Vlad)
# ---------------------------------------------------------------------------
MARS_TRINE: tuple[SourceFactDef, ...] = (
    _f("mars_tr_word_connects_with_action", "aspect", "trine_Mars", "work_application",
       "Word connects easily and quickly with action.",
       "strength", "thought_to_action", "fast_thinking",
       source_reference=REF_MARS_HARM),
    _f("mars_tr_thinking_faster", "aspect", "trine_Mars", "thinking",
       "Thinking becomes faster.",
       "strength", "fast_thinking",
       source_reference=REF_MARS_HARM),
    _f("mars_tr_thinking_sharper", "aspect", "trine_Mars", "thinking",
       "Thinking becomes sharper.",
       "strength", "fast_thinking",
       source_reference=REF_MARS_HARM),
    _f("mars_tr_thinking_more_analytical", "aspect", "trine_Mars", "thinking",
       "Thinking becomes more analytical.",
       "strength", "analytical_thinking",
       source_reference=REF_MARS_HARM),
    _f("mars_tr_easier_to_argue_debate", "aspect", "trine_Mars", "communication",
       "Easier to argue / debate.",
       "strength", "debate",
       source_reference=REF_MARS_HARM),
    _f("mars_tr_persuasive", "aspect", "trine_Mars", "communication",
       "Persuasive.",
       "strength", "persuasion",
       source_reference=REF_MARS_HARM),
    _f("mars_tr_speech_clearer_more_forceful", "aspect", "trine_Mars", "communication",
       "Speech becomes louder / clearer and more forceful.",
       "strength", "forceful_speech",
       source_reference=REF_MARS_HARM),
    _f("mars_tr_action_more_rational", "aspect", "trine_Mars", "work_application",
       "Action becomes more rational.",
       "strength", "thought_to_action",
       source_reference=REF_MARS_HARM),
    _f("mars_tr_supports_multitasking", "aspect", "trine_Mars", "thinking",
       "Supports multitasking.",
       "strength", "multitasking",
       source_reference=REF_MARS_HARM),
    _f("mars_tr_speak_learn_act_simultaneously", "aspect", "trine_Mars", "work_application",
       "Easier to speak, learn and act simultaneously.",
       "strength", "multitasking", "thought_to_action", "fast_thinking",
       source_reference=REF_MARS_HARM),
)

# ---------------------------------------------------------------------------
# Mercury sextile Jupiter (Vlad)
# ---------------------------------------------------------------------------
JUPITER_SEXTILE: tuple[SourceFactDef, ...] = (
    _f("jupiter_sx_analysis_connects_with_synthesis", "aspect", "sextile_Jupiter", "thinking",
       "Analysis connects with synthesis.",
       "strength", "analysis_synthesis",
       source_reference=REF_JUPITER_HARM),
    _f("jupiter_sx_learning_connects_with_teaching", "aspect", "sextile_Jupiter", "learning",
       "Learning connects with teaching.",
       "strength", "teaching_learning", "teaching",
       source_reference=REF_JUPITER_HARM),
    _f("jupiter_sx_native_and_foreign_languages", "aspect", "sextile_Jupiter", "communication",
       "Native language / communication connects with foreign languages.",
       "strength", "foreign_languages",
       source_reference=REF_JUPITER_HARM),
    _f("jupiter_sx_aptitude_foreign_languages", "aspect", "sextile_Jupiter", "learning",
       "Aptitude / interest in foreign languages.",
       "strength", "foreign_languages",
       source_reference=REF_JUPITER_HARM),
    _f("jupiter_sx_legal_aptitude", "aspect", "sextile_Jupiter", "work_application",
       "Legal aptitude.",
       "strength", "legal_aptitude",
       source_reference=REF_JUPITER_HARM),
    _f("jupiter_sx_oratory_and_persuasion", "aspect", "sextile_Jupiter", "communication",
       "Oratory and persuasion.",
       "strength", "oratory", "persuasion",
       source_reference=REF_JUPITER_HARM),
    _f("jupiter_sx_need_to_learn_and_expand", "aspect", "sextile_Jupiter", "learning",
       "Continuing need to learn and expand horizons.",
       "strength", "lifelong_learning", "broad_knowledge_orientation",
       source_reference=REF_JUPITER_HARM),
    _f("jupiter_sx_interest_philosophy", "aspect", "sextile_Jupiter", "learning",
       "Interest in philosophy.",
       "neutral", "philosophy_interest", "broad_knowledge_orientation",
       source_reference=REF_JUPITER_HARM),
    _f("jupiter_sx_interest_science", "aspect", "sextile_Jupiter", "learning",
       "Interest in science.",
       "strength", "science_interest", "broad_knowledge_orientation",
       source_reference=REF_JUPITER_HARM),
    _f("jupiter_sx_interest_esoteric_abstract", "aspect", "sextile_Jupiter", "learning",
       "Interest in esoteric / abstract knowledge.",
       "neutral", "esoteric_abstract_interest", "broad_knowledge_orientation",
       source_reference=REF_JUPITER_HARM),
    _f("jupiter_sx_low_expression_excessive_empty_talking", "aspect", "sextile_Jupiter", "risk",
       "Possible low-development expression: excessive / empty talking.",
       "risk", "empty_talking",
       source_reference=REF_JUPITER_HARM),
)

# ---------------------------------------------------------------------------
# Mercury in Sagittarius (Dzmitry)
# ---------------------------------------------------------------------------
SAGITTARIUS_GENERAL: tuple[SourceFactDef, ...] = (
    _f("sag_thinks_in_categories_globally", "sign", "Sagittarius", "thinking",
       "Thinks in categories, globally, on a large scale.",
       "strength", "global_thinking",
       source_reference=REF_SAGITTARIUS),
    _f("sag_asks_why_what_for", "sign", "Sagittarius", "thinking",
       "Asks \"why?\" / \"what for?\".",
       "neutral", "higher_meaning",
       source_reference=REF_SAGITTARIUS),
    _f("sag_searches_higher_meaning_in_ordinary", "sign", "Sagittarius", "thinking",
       "Searches for higher meaning even in ordinary things.",
       "strength", "higher_meaning",
       source_reference=REF_SAGITTARIUS),
    _f("sag_sees_elevated_misses_simple", "sign", "Sagittarius", "thinking",
       "Sees elevated / large meaning while missing the simple.",
       "risk", "higher_meaning", "global_thinking",
       source_reference=REF_SAGITTARIUS),
    _f("sag_nonstandard_in_intellectual_matters", "sign", "Sagittarius", "thinking",
       "Nonstandard in intellectual matters.",
       "strength", "nonstandard_thinking",
       source_reference=REF_SAGITTARIUS),
    _f("sag_difficulty_theory_to_practice", "sign", "Sagittarius", "learning",
       "Difficulty moving from theory to practice.",
       "risk", "theory_practice_gap",
       source_reference=REF_SAGITTARIUS),
    _f("sag_speaks_like_preacher_agitator_philosopher", "sign", "Sagittarius", "communication",
       "Speaks like a preacher / agitator / philosopher.",
       "neutral", "teaching", "authority_through_speech",
       source_reference=REF_SAGITTARIUS),
    _f("sag_speech_maintains_authority", "sign", "Sagittarius", "communication",
       "Speech is used to maintain authority.",
       "neutral", "authority_through_speech",
       source_reference=REF_SAGITTARIUS),
    _f("sag_tends_to_teach_lecture", "sign", "Sagittarius", "communication",
       "Tends to teach / lecture others.",
       "neutral", "teaching",
       source_reference=REF_SAGITTARIUS),
    _f("sag_tendency_to_attach_labels", "sign", "Sagittarius", "communication",
       "Tendency to attach labels.",
       "risk", "authority_through_speech",
       source_reference=REF_SAGITTARIUS),
    _f("sag_broadcasts_from_above", "sign", "Sagittarius", "communication",
       "Broadcasts ideas from above rather than entering equal dialogue.",
       "risk", "dialogue_difficulty", "authority_through_speech",
       source_reference=REF_SAGITTARIUS),
    _f("sag_calculation_errors_neglect_precision", "sign", "Sagittarius", "risk",
       "Calculation errors / neglect of precision.",
       "risk", "precision_risk",
       source_reference=REF_SAGITTARIUS),
    _f("sag_learning_pass_knowledge_to_others", "sign", "Sagittarius", "learning",
       "Passing learned knowledge to other people supports learning.",
       "strength", "teaching", "goal_motivated_learning",
       source_reference=REF_SAGITTARIUS),
    _f("sag_learning_university_textbooks", "sign", "Sagittarius", "learning",
       "University-level textbooks support learning.",
       "neutral", "goal_motivated_learning",
       source_reference=REF_SAGITTARIUS),
    _f("sag_learning_encyclopedias", "sign", "Sagittarius", "learning",
       "Encyclopedias support learning.",
       "neutral", "goal_motivated_learning",
       source_reference=REF_SAGITTARIUS),
    _f("sag_learning_practical_life_motive", "sign", "Sagittarius", "learning",
       "Finding a practical / life motive for why the learning matters supports learning.",
       "neutral", "goal_motivated_learning",
       source_reference=REF_SAGITTARIUS),
    _f("sag_learning_setting_a_goal", "sign", "Sagittarius", "learning",
       "Setting a goal supports learning.",
       "neutral", "goal_motivated_learning",
       source_reference=REF_SAGITTARIUS),
    _f("sag_love_of_pompous_wording", "sign", "Sagittarius", "communication",
       "Love of pompous / high-flown wording.",
       "risk", "precision_risk",
       source_reference=REF_SAGITTARIUS),
    _f("sag_intolerance_of_others_opinions", "sign", "Sagittarius", "communication",
       "Intolerance of other people's opinions and ideas.",
       "risk", "dialogue_difficulty",
       source_reference=REF_SAGITTARIUS),
    _f("sag_theory_to_practice_gap_risk", "sign", "Sagittarius", "risk",
       "Theory-to-practice gap.",
       "risk", "theory_practice_gap",
       source_reference=REF_SAGITTARIUS),
    _f("sag_seeks_socially_significant_fashionable", "sign", "Sagittarius", "environment",
       "Seeks socially significant / fashionable people or themes in the environment.",
       "neutral", "prestige_orientation",
       source_reference=REF_SAGITTARIUS),
    _f("sag_teacher_like_with_siblings", "sign", "Sagittarius", "environment",
       "Teacher-like position with siblings.",
       "neutral", "teaching",
       source_reference=REF_SAGITTARIUS),
    _f("sag_lecturing_labeling_siblings", "sign", "Sagittarius", "environment",
       "Lecturing / labeling siblings.",
       "risk", "teaching", "authority_through_speech",
       source_reference=REF_SAGITTARIUS),
    _f("sag_tells_others_about_achievements", "sign", "Sagittarius", "communication",
       "Likes telling others about own achievements / exploits.",
       "neutral", "authority_through_speech",
       source_reference=REF_SAGITTARIUS),
)

# ---------------------------------------------------------------------------
# Mercury in House 10 (Dzmitry)
# ---------------------------------------------------------------------------
HOUSE_10: tuple[SourceFactDef, ...] = (
    _f("h10_reputation_exceptional_intellect", "house", "10", "work_application",
       "Reputation of a person of exceptional intellect.",
       "strength", "intellectual_reputation",
       source_reference=REF_H10),
    _f("h10_democratic_relationship_with_leadership", "house", "10", "work_application",
       "Democratic relationship with leadership based on shared intellectual interests.",
       "strength", "leadership_communication",
       source_reference=REF_H10),
    _f("h10_mission_informing_people", "house", "10", "work_application",
       "Mission / role of informing people.",
       "strength", "informing_people",
       source_reference=REF_H10),
    _f("h10_career_requires_communication_tools", "house", "10", "work_application",
       "Career success may require mastering communication tools.",
       "neutral", "leadership_communication",
       source_reference=REF_H10),
    _f("h10_career_requires_large_information_volumes", "house", "10", "work_application",
       "Career success may require processing very large information volumes.",
       "neutral", "large_information_load",
       source_reference=REF_H10),
    _f("h10_information_load_can_be_difficult", "house", "10", "risk",
       "That information load can be difficult.",
       "risk", "large_information_load",
       source_reference=REF_H10),
    _f("h10_knowledge_for_prestige_not_curiosity", "house", "10", "risk",
       "Knowledge may be pursued for benefit / prestige / honor rather than curiosity.",
       "risk", "prestige_orientation",
       source_reference=REF_H10),
    _f("h10_many_connections_reduced_independence", "house", "10", "environment",
       "Many connections but reduced independence.",
       "risk", "prestige_orientation",
       source_reference=REF_H10),
    _f("h10_frequent_change_of_work", "house", "10", "work_application",
       "Frequent change of work activity.",
       "neutral", "career_change",
       source_reference=REF_H10),
    _f("h10_may_change_professions_until_interesting_prestigious", "house", "10", "work_application",
       "May change professions until finding \"interesting + prestigious\".",
       "neutral", "career_change", "prestige_orientation",
       source_reference=REF_H10),
    _f("h10_interest_in_ranks", "house", "10", "work_application",
       "Interest in ranks.",
       "neutral", "prestige_orientation",
       source_reference=REF_H10),
    _f("h10_interest_in_titles", "house", "10", "work_application",
       "Interest in titles.",
       "neutral", "prestige_orientation",
       source_reference=REF_H10),
    _f("h10_interest_in_distinctions_status_markers", "house", "10", "work_application",
       "Interest in distinctions / status markers.",
       "neutral", "prestige_orientation",
       source_reference=REF_H10),
)

# ---------------------------------------------------------------------------
# Mercury conjunction Uranus (Dzmitry) — conjunction-specific pack
# ---------------------------------------------------------------------------
URANUS_CONJUNCTION: tuple[SourceFactDef, ...] = (
    _f("uranus_cj_function_overridden_by_rebellious_superconsciousness", "aspect", "conjunction_Uranus", "thinking",
       "Communication and learning function is strongly overridden / transformed by rebellious technical \"super-consciousness\".",
       "neutral", "rebellious_free_thinking", "technical_ability",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_resembles_square_when_uranus_stronger", "aspect", "conjunction_Uranus", "source_specific",
       "Source relationship: this configuration resembles the Mercury–Uranus square when Uranus is stronger (reference only; square pack is not auto-activated).",
       "neutral", "source_relationship",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_genius_potential", "aspect", "conjunction_Uranus", "thinking",
       "Genius potential.",
       "strength", "future_intellect",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_freshness_of_mind", "aspect", "conjunction_Uranus", "thinking",
       "Freshness of mind.",
       "strength", "open_mind",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_openness_of_mind", "aspect", "conjunction_Uranus", "thinking",
       "Openness of mind.",
       "strength", "open_mind",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_technical_talent", "aspect", "conjunction_Uranus", "work_application",
       "Technical talent.",
       "strength", "technical_ability",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_rebellious_free_thinking", "aspect", "conjunction_Uranus", "thinking",
       "Rebellious / free thinking.",
       "strength", "rebellious_free_thinking", "nonstandard_thinking",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_spontaneous_creativity", "aspect", "conjunction_Uranus", "thinking",
       "Spontaneous creativity.",
       "strength", "spontaneous_creativity",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_intellect_of_the_future", "aspect", "conjunction_Uranus", "source_specific",
       "Source-described potential: \"intellect of the future\".",
       "strength", "future_intellect",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_distractibility_loss_of_focus", "aspect", "conjunction_Uranus", "risk",
       "Distractibility / loss of focus.",
       "risk", "distractibility",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_adhd_like_attention_scatter", "aspect", "conjunction_Uranus", "risk",
       "Source uses ADHD wording for attention-scatter / distractibility (source-described, non-diagnostic; not a medical conclusion).",
       "risk", "distractibility",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_drifting_into_strange_concepts", "aspect", "conjunction_Uranus", "risk",
       "Drifting into strange / unusual concepts.",
       "risk", "strange_concept_drift",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_impractical_thinking", "aspect", "conjunction_Uranus", "risk",
       "Impractical thinking.",
       "risk", "impractical_thinking",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_boredom_with_here_and_now", "aspect", "conjunction_Uranus", "risk",
       "Boredom with thinking only about the here-and-now.",
       "risk", "future_intellect",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_fast_speech", "aspect", "conjunction_Uranus", "communication",
       "Fast speech.",
       "neutral", "fast_speech",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_speech_may_become_disjointed", "aspect", "conjunction_Uranus", "communication",
       "Speech may sometimes become disjointed.",
       "risk", "fast_speech",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_speech_may_become_compressed", "aspect", "conjunction_Uranus", "communication",
       "Speech may become compressed / crumpled.",
       "risk", "fast_speech",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_strong_sense_of_humor", "aspect", "conjunction_Uranus", "communication",
       "Strong sense of humor.",
       "strength", "humor",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_piercing_unusual_persuasiveness", "aspect", "conjunction_Uranus", "communication",
       "Piercing / unusual persuasiveness of speech.",
       "strength", "persuasion",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_accident_driving_risk", "aspect", "conjunction_Uranus", "mobility",
       "Increased accident / driving risk source signal.",
       "risk", "driving",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_interest_psychology", "aspect", "conjunction_Uranus", "learning",
       "Interest / ability in psychology.",
       "neutral", "psychology_interest",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_interest_numerology", "aspect", "conjunction_Uranus", "learning",
       "Interest / ability in numerology.",
       "neutral", "esoteric_abstract_interest",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_interest_astrology", "aspect", "conjunction_Uranus", "learning",
       "Interest / ability in astrology.",
       "neutral", "esoteric_abstract_interest",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_claircognizance", "aspect", "conjunction_Uranus", "source_specific",
       "Source-specific / esoteric claim: claircognizance.",
       "neutral", "source_specific_esoteric",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_antenna_with_cosmos", "aspect", "conjunction_Uranus", "source_specific",
       "Source-specific / esoteric claim: \"antenna with cosmos\".",
       "neutral", "source_specific_esoteric", "future_intellect",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_intellectual_chosenness_elitism", "aspect", "conjunction_Uranus", "secondary_gain",
       "Secondary gain: intellectual chosenness / intellectual elitism.",
       "neutral", "intellectual_elitism",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_comp_laugh_joke_satire", "aspect", "conjunction_Uranus", "compensation",
       "Source compensation idea: laugh / joke / mock / use satire.",
       "neutral", "humor", "compensation",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_comp_astrology_esotericism", "aspect", "conjunction_Uranus", "compensation",
       "Source compensation idea: astrology / esotericism.",
       "neutral", "compensation", "esoteric_abstract_interest",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_comp_read_science_fiction", "aspect", "conjunction_Uranus", "compensation",
       "Source compensation idea: read science fiction.",
       "neutral", "compensation", "future_intellect",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_comp_read_about_future", "aspect", "conjunction_Uranus", "compensation",
       "Source compensation idea: read about the future.",
       "neutral", "compensation", "future_intellect",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_comp_dissertation_deep_academic", "aspect", "conjunction_Uranus", "compensation",
       "Source compensation idea: dissertation / deep academic work.",
       "neutral", "compensation",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_comp_mathematics", "aspect", "conjunction_Uranus", "compensation",
       "Source compensation idea: mathematics.",
       "neutral", "compensation", "technical_ability",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_comp_forecasting", "aspect", "conjunction_Uranus", "compensation",
       "Source compensation idea: forecasting.",
       "neutral", "compensation", "future_intellect",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_comp_speed_reading", "aspect", "conjunction_Uranus", "compensation",
       "Source compensation idea: speed reading.",
       "neutral", "compensation",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_comp_super_memory_practices", "aspect", "conjunction_Uranus", "compensation",
       "Source compensation idea: super-memory practices (source wording).",
       "neutral", "compensation", "memory",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_comp_discussion_with_friends", "aspect", "conjunction_Uranus", "compensation",
       "Source compensation idea: discussion with friends.",
       "neutral", "compensation",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_comp_home_discussion_club", "aspect", "conjunction_Uranus", "compensation",
       "Source compensation idea: home discussion club.",
       "neutral", "compensation",
       source_reference=REF_URANUS_CONJ),
    _f("uranus_cj_comp_formula1_high_speed_stimulation", "aspect", "conjunction_Uranus", "compensation",
       "Source compensation idea: Formula 1 / high-speed technical stimulation.",
       "neutral", "compensation",
       source_reference=REF_URANUS_CONJ),
)

# Aspect keys that reuse another pack's catalog definitions (shared source semantics).
ASPECT_PACK_ALIASES: dict[str, str] = {
    "sextile_Mars": "trine_Mars",
}

SUPPORTED_SIGN_KEYS = {"Aries", "Taurus", "Gemini", "Cancer", "Leo", "Sagittarius"}
SUPPORTED_HOUSE_KEYS = {"1", "9", "10"}
SUPPORTED_MOTION_KEYS = {"retrograde"}
SUPPORTED_ASPECT_KEYS = {
    "square_Pluto",
    "trine_Saturn",
    "sextile_Moon",
    "square_Moon",
    "trine_Mars",
    "sextile_Mars",
    "sextile_Jupiter",
    "conjunction_Uranus",
}

# Late import: A1 packs depend on SourceFactDef/_f defined above.
from app.services.mercury_source_knowledge_a1_signs import (  # noqa: E402
    A1_SIGN_PACKS,
    ARIES_ALL,
    CANCER_ALL,
    GEMINI_ALL,
)

ALL_SOURCE_FACTS: tuple[SourceFactDef, ...] = (
    LEO_GENERAL
    + LEO_AFFLICTED
    + HOUSE_1
    + RETROGRADE
    + PLUTO_SQUARE
    + SATURN_TRINE
    + MOON_SEXTILE
    + TAURUS_GENERAL
    + HOUSE_9
    + MOON_SQUARE
    + MARS_TRINE
    + JUPITER_SEXTILE
    + SAGITTARIUS_GENERAL
    + HOUSE_10
    + URANUS_CONJUNCTION
    + A1_SIGN_PACKS
)

# Repeated-signal definitions: SAME tag across distinct provenance keys only.
# No also_accept unions — nearby concepts must not be merged.
REPEATED_SIGNAL_SPECS: tuple[dict, ...] = (
    {
        "signal": "strong_memory",
        "tag": "memory",
        "min_factor_keys": 2,
    },
    {
        "signal": "analytical_thinking",
        "tag": "analytical_thinking",
        "min_factor_keys": 2,
    },
    {
        "signal": "technical_ability",
        "tag": "technical_ability",
        "min_factor_keys": 2,
    },
    {
        "signal": "insight_seeing_not_obvious",
        "tag": "insight",
        "min_factor_keys": 2,
    },
    {
        "signal": "debate",
        "tag": "debate",
        "min_factor_keys": 2,
    },
    {
        "signal": "argumentation",
        "tag": "argumentation",
        "min_factor_keys": 2,
    },
    {
        "signal": "persuasion",
        "tag": "persuasion",
        "min_factor_keys": 2,
    },
    {
        "signal": "evidence_requirement",
        "tag": "evidence_requirement",
        "min_factor_keys": 2,
    },
    {
        "signal": "nonstandard_thinking",
        "tag": "nonstandard_thinking",
        "min_factor_keys": 2,
    },
    {
        "signal": "nonstandard_learning",
        "tag": "nonstandard_learning",
        "min_factor_keys": 2,
    },
    {
        "signal": "sales",
        "tag": "sales",
        "min_factor_keys": 2,
    },
    {
        "signal": "lifelong_learning",
        "tag": "lifelong_learning",
        "min_factor_keys": 2,
    },
    {
        "signal": "foreign_languages",
        "tag": "foreign_languages",
        "min_factor_keys": 2,
    },
    {
        "signal": "analytical_plus_abstract",
        "tag": "analytical_plus_abstract",
        "min_factor_keys": 2,
    },
    {
        "signal": "teaching",
        "tag": "teaching",
        "min_factor_keys": 2,
    },
    {
        "signal": "fast_thinking",
        "tag": "fast_thinking",
        "min_factor_keys": 2,
    },
)

CONTRAST_PAIRS: tuple[tuple[str, str], ...] = (
    ("superficiality", "depth"),
    ("superficiality", "analytical_thinking"),
    ("soft_speech", "sharp_speech"),
    ("deliberate_processing", "fast_thinking"),
    ("deliberate_processing", "mental_switching_pressure"),
    ("global_thinking", "precision_risk"),
)
